const productData = {
  'Bảng cảnh báo': {
    names: [
      'Biển Cảnh Báo Nguy Hiểm Điện Áp Cao',
      'Bảng Cấm Vào Khu Vực Nguy Hiểm',
      'Biển Báo An Toàn Lao Động Phản Quang',
      'Bảng Nội Quy Công Trình Inox 304',
      'Biển Cảnh Báo Phóng Điện - Nguy Hiểm Chết Người',
      'Bảng Cảnh Báo Hóa Chất Độc Hại ISO',
    ],
    descs: [
      'Biển cảnh báo nhựa PVC cao cấp, chữ in sắc nét, chống UV và thời tiết. Đạt tiêu chuẩn ISO 3864 về ký hiệu an toàn lao động.',
      'Bảng nhôm dày 1.2mm, in sơn phản quang ban đêm. Kích thước 30x40cm, lỗ treo sẵn, chịu được nhiệt độ -20°C đến 80°C.',
      'Biển báo composite hai lớp, mặt nhám chống chói, màu sắc tiêu chuẩn QCVN AT-HĐ:2012 của Bộ Lao Động.',
      'Bảng inox 304 đánh bóng, laser khắc chữ sâu 0.3mm, không phai màu. Chịu ăn mòn hóa chất, phù hợp môi trường nhà máy.',
      'Biển cảnh báo phản quang loại 3M, nhìn rõ từ 100m kể cả ban đêm. Gắn cột hoặc tường bằng vít inox đi kèm.',
      'Bảng cảnh báo hóa chất theo tiêu chuẩn GHS/CLP, in màu bền, không ố vàng sau 5 năm ngoài trời.',
    ],
  },
  'Cuộn rào công trình': {
    names: [
      'Lưới Rào Chắn Công Trình Màu Cam Loại Dày',
      'Cuộn Lưới Báo Hiệu Ngăn Cách HDPE',
      'Rào Chắn Công Trình Dạng Cuộn 50m Chuyên Nghiệp',
      'Dây Cảnh Báo Nguy Hiểm Loại Dây Quanh Vùng Nguy Hiểm',
      'Lưới Bảo Vệ Thi Công Chống Người Lọt Xuống Hố',
      'Rào Cách Ly Thi Công Màu Vàng Đen PE Cao Cấp',
      'Lưới Che Chắn Bụi Công Trình Dạng Cuộn 100m',
      'Cuộn Lưới Polyethylene Phản Quang Công Trình Đô Thị',
    ],
    descs: [
      'Lưới HDPE nguyên sinh màu cam, độ dày 1.5mm, chịu kéo 800N/5cm. Cuộn 50m, chiều cao 1.2m, có lỗ buộc dây dễ dàng.',
      'Dây polyethylene tái chế cao cấp, màu vàng đen xen kẽ, in chữ NGUY HIỂM liên tục. Cuộn 200m, chịu được mưa nắng 2 năm.',
      'Lưới rào chắn PE đan mắt 5x5cm, kéo dài không đứt, màu cam phản quang. Dùng tại công trường, khu vực nguy hiểm hạn chế người vào.',
      'Dây cảnh báo 2 màu vàng-đen, đường kính 6mm, cuộn 500m. Dễ dàng kéo dài, buộc cọc hoặc cọc nhựa bán kèm.',
      'Lưới bảo vệ hố đào PE màu đỏ, chịu tải 120kg/m², kích thước mắt lưới 3x3cm. Giúp ngăn ngã xuống hố đào.',
      'Rào cách ly màu vàng đen 1.0m x 25m, trọng lượng nhẹ, gấp gọn bảo quản dễ. Thường dùng ngăn cách khu vực vệ sinh đường.',
      'Lưới che bụi xây dựng màu xanh HDPE, kích thước mắt 1.5mm, chặn 90% bụi. Chiều cao 2m, cuộn 100m, bền 3-5 năm.',
      'Cuộn lưới PE phản quang hai lớp, tích hợp sợi phản quang 3M, quan sát được ban đêm từ 50m. Tiêu chuẩn công trình đô thị.',
    ],
  },
  'Cà Vạt, Ve Bảo Vệ': {
    names: [
      'Cà Vạt Bảo Vệ Màu Đen Bóng Cao Cấp',
      'Ve Cổ Áo Bảo Vệ Inox Mạ Vàng',
      'Cà Vạt Đồng Phục Bảo Vệ Sọc Xanh Đen',
      'Phù Hiệu Ve Cổ Áo Bảo Vệ Đúc Kim Loại',
    ],
    descs: [
      'Cà vạt polyester cao cấp, bề mặt bóng mịn, màu đen thuần. Độ dài 145cm, khóa nam châm tiện lợi, không cần buộc nút thắt.',
      'Ve cổ áo bảo vệ hợp kim kẽm mạ vàng, logo khắc nổi, ghim cài chắc chắn. Kích thước 4x2.5cm, bộ 2 cái.',
      'Cà vạt sọc xanh đen polyester chống nhăn, chống bám bụi. Có kẹp cà vạt inox đi kèm, phù hợp đồng phục bảo vệ chuyên nghiệp.',
      'Phù hiệu ve cổ đồng mạ chrome, in chìm SECURITY/BẢO VỆ. Đính kèm ghim an toàn chắc chắn, không rỉ sét.',
    ],
  },
  'Cầu Vai Bảo Vệ': {
    names: [
      'Cầu Vai Bảo Vệ Loại Ngôi Sao Vàng 3 Cánh',
      'Phù Hiệu Cầu Vai Bảo Vệ Mạ Vàng Cao Cấp',
      'Cầu Vai Đồng Phục Bảo Vệ Sọc Vàng 2 Vạch',
      'Phù Hiệu Vai Áo Bảo Vệ Chuyên Nghiệp Inox',
      'Cầu Vai Trang Trí Áo Bảo Vệ Vải Dệt Kim Loại',
    ],
    descs: [
      'Cầu vai ngôi sao 3 cánh mạ vàng 24K, hợp kim kẽm cao cấp. Đi kèm clip gắn vai, tương thích áo bảo vệ loại cầu vai dán/kẹp.',
      'Phù hiệu vai bảo vệ đồng thau mạ vàng, khắc nổi cấp hiệu rõ ràng. Kích thước 10x4cm, ghim chắc, không phai màu 3 năm.',
      'Cầu vai sọc vàng trên nền đen 2 vạch, chất liệu polyester với chỉ vàng dệt. Bộ 2 chiếc, vá may hoặc dán lên áo.',
      'Phù hiệu vai inox 316 đánh bóng, laser khắc logo, không gỉ sét trong môi trường ẩm. Kích thước 8x3.5cm, gắn epaulette chuẩn.',
      'Cầu vai trang trí dệt chỉ vàng bạc, bề dày 5mm. Đính sẵn 2 cúc đồng, có thể gắn thêm phù hiệu ngôi sao.',
    ],
  },
  'Cọc giao thông-cột chia làn đường': {
    names: [
      'Cọc Tiêu Giao Thông Nhựa PE Màu Cam 75cm',
      'Cột Phân Làn Đường Cao Su Đặc Chống Va Đập',
      'Cọc Barricade Nhựa Màu Đỏ Trắng Phản Quang',
      'Cột Chia Làn Đường Cao Su 1m Chân Đế Nặng',
      'Cọc Tiêu Phản Quang Loại Dẹt Gắn Lề Đường',
      'Cọc Nhựa Phân Làn Đường Loại Cứng ABS 100cm',
      'Cột Phân Làn Cao Su Đàn Hồi Chống Gãy 500mm',
      'Cọc Hướng Dẫn Giao Thông Nhựa PE Phản Quang',
      'Cột Chia Tuyến Đường Bộ Dạng Con Thuyền',
      'Cọc Tiêu Phân Cách Làn Đường Nhựa HDPE 80cm',
      'Cột Phân Cách Đường Đôi Cao Su Đặc 70cm',
      'Cột Nhựa Phân Làn Đường Tốc Độ Cao Dạng Ống',
      'Cọc Báo Hiệu Lề Đường Phản Quang Cát Đinh',
      'Cọc Tiêu Biên Giới Đường Nhựa Cứng 1.2m',
      'Cột Phân Làn Uốn Đàn Hồi Nhựa EVA 80cm',
    ],
    descs: [
      'Cọc tiêu nhựa PE nguyên sinh màu cam sáng, cao 75cm, đường kính 8cm. Phản quang cấp độ 2 (RA≥250 cd/lux/m²), nhìn rõ 200m ban đêm.',
      'Cột phân làn cao su đặc tự nhiên, cao 1m, đường kính 10cm. Chịu va đập xe hạng nặng, bật lại hình dạng ban đầu trong 2 giây.',
      'Cọc barricade đỏ trắng xen kẽ 5cm mỗi dải, nhựa ABS cứng. Phản quang 3M loại 1, nhìn rõ 150m đêm có đèn pha xe.',
      'Cột chia làn cao su đặc 1m, chân đế 30x30cm nặng 8kg chống ngã. Có lỗ xâu dây hoặc gắn thanh ngang liên kết cọc.',
      'Cọc tiêu dẹt dài 400mm, gắn mép lề đường bằng đinh thép inox. Phản quang hai mặt, chịu được bánh xe cán qua không vỡ.',
      'Cọc nhựa ABS cứng 100cm, màu cam, thân tròn đường kính 7.5cm. Khoan lỗ gắn bu-lông xuống mặt đường hoặc chân rời tháo lắp.',
      'Cột cao su đàn hồi 500mm, khi xe cán sẽ nằm xuống rồi bật lại. Ứng dụng làn dừng xe buýt, bãi giữ xe, khu vực đông người.',
      'Cọc hướng dẫn giao thông PE 80cm, in vạch phản quang đen-trắng-cam. Thường dùng phân làn thi công đường hoặc sự cố giao thông.',
      'Cột phân cách dạng con thuyền nhựa HDPE, dài 1m, cao 45cm. Có thể liên kết thành hàng dài bằng khớp nối nhựa đi kèm.',
      'Cọc tiêu phân cách 80cm, nhựa HDPE tái chế cao cấp, không phai màu. Phản quang 3 mặt, góc nhìn 180°, tiêu chuẩn Bộ GTVT.',
      'Cột đôi phân cách đường bộ, cao su đặc 70cm, nặng 3.5kg. Ổn định không nghiêng ngả khi có gió mạnh hoặc xe đi qua gần.',
      'Cột ống nhựa phân làn đường cao tốc, PVC dày 5mm, cao 1.2m. Phần đầu cột gắn phản quang bi 40x40cm thay thế được.',
      'Cọc báo hiệu lề đường kèm cát đinh thép phản quang, cắm thẳng vào đất. Cao 60cm, đầu cọc có đèn LED solar option.',
      'Cọc tiêu biên giới nhựa cứng 1.2m, dùng đánh dấu ranh giới đường. Thân màu trắng, vạch phản quang đỏ-cam, đế cắm đất sâu 30cm.',
      'Cột phân làn EVA đàn hồi 80cm, siêu nhẹ 600g, bật lại hoàn toàn khi bị xe cán. Màu vàng huỳnh quang, dùng ban ngày lẫn đêm.',
    ],
  },
  'Dây an toàn': {
    names: [
      'Dây An Toàn Đơn Khóa Móc Inox 316 Tải 1500kg',
      'Bộ Dây An Toàn Kép Hấp Thụ Lực EN354',
      'Dây Giữ Thăng Bằng Lanyard Dệt Polyester 2m',
      'Dây An Toàn Có Hộp Thu Tự Động 3m',
      'Dây Bảo Hiểm Cơ Thể Nối Đai An Toàn',
      'Dây Chống Ngã Có Lò Xo Hấp Thụ Lực',
      'Dây An Toàn Thoát Hiểm Khẩn Cấp 10m',
      'Dây Lanyard Cứu Hộ Kép Móc Snaphook Thép',
      'Dây Bảo Hộ Leo Cao Chuyên Nghiệp Petzl',
      'Dây Gắn Móc Inox Tải 2200kg Tiêu Chuẩn CE',
      'Dây An Toàn Polyamide 11mm Cho Công Nhân Xây Dựng',
      'Dây An Toàn 1.5m Móc Khóa Xoay 360° Thép',
      'Dây Cứu Hộ Dệt Polyester Lõi Thép 3m',
      'Dây An Toàn Đôi Thứ Cấp Dự Phòng 2x1m',
      'Dây Bảo Hiểm Giảm Chấn Nefab Tiêu Chuẩn ANSI',
      'Dây An Toàn Điều Chỉnh Độ Dài 1-1.8m',
      'Dây Cầm Tay Bảo Hiểm Ngắn 30cm Móc Inox',
      'Dây Chống Ngã Loại Dệt Thoi Polyester 16mm',
      'Dây An Toàn Hấp Thụ Lực 1.75m Chuẩn EN355',
      'Dây Bảo Hiểm Loại Cuộn Tự Thu 2m Nhựa Vỏ',
      'Dây Bảo Hộ Mái Nhà Kép Cơ Cấu Giảm Xóc',
      'Dây An Toàn Chữ Y Kép 1.2m Móc Thép Mạ',
      'Dây Bảo Hiểm Cấu Trúc Thép Lõi Polyester',
      'Dây Thoát Hiểm Cuộn Tự Động Sàn Cao Tầng',
    ],
    descs: [
      'Dây đơn polyester dệt thoi 16mm, dài 1.8m, móc inox 316 tải 1500kg. Hấp thụ lực giảm chấn khi ngã, đạt EN354/EN355.',
      'Bộ dây kép chữ Y, mỗi nhánh 1m, hộp giảm chấn 200J. Tải 500kg mỗi nhánh, móc khóa tự động thép mạ chrome, đạt EN354.',
      'Lanyard dệt polyester 25mm, dài 2m, không giảm chấn. Dùng định vị - không dùng ngã tự do. Móc snaphook thép 25kN.',
      'Dây cuộn thu tự động lò xo 3m, vỏ nhựa ABS chịu lực. Ra dây tự do, khi ngã khóa tức thì trong 0.1s. Tải 150kg.',
      'Dây bảo hiểm thân kết nối điểm neo trên đai ngực và đai vai. Polyester 2 lớp, dài 0.5m, móc inox 40kN hai hướng.',
      'Dây chống ngã lò xo hấp thụ lực, dạng accordion, co giãn 0.5-1.5m. Nổ hộp giảm chấn khi lực vượt 4kN, bảo vệ cột sống.',
      'Dây thoát hiểm 10m, polyamide 11mm, cuộn dạng tám hãm. Dùng cho nhân viên thoát khẩn cấp từ tòa nhà, tốc độ kiểm soát.',
      'Dây lanyard kép móc snaphook thép mạ kẽm 23kN, dài 1+1m chữ Y. Vỏ bảo vệ hộp giảm chấn dứt dây tại 4-5kN.',
      'Dây leo cao Petzl Grillon 1.9m, polyamide/Dyneema, trọng lượng 195g. Khóa trượt 2 chiều, tự điều chỉnh theo vị trí làm việc.',
      'Dây gắn móc inox 304, đường kính 12mm, dài 1m, tải tĩnh 2200kg. Cáp thép lõi 6x7, bọc nhựa PVC bảo vệ, CE/ISO 9001.',
      'Dây polyamide 11mm loại B dành cho xây dựng, cuộn 50m. Độ dãn <5% tại 2kN, chịu mài mòn và tia UV tốt.',
      'Dây 1.5m gắn móc khóa xoay 360° thép 23kN. Tránh xoắn dây khi làm việc, tăng an toàn di chuyển vòng quanh điểm neo.',
      'Dây cứu hộ dệt polyester lõi thép 3m, chịu tải 5000kg. Dùng trong cứu hỏa, tìm kiếm cứu nạn, leo núi công nghiệp.',
      'Dây đôi thứ cấp 2x1m chữ Y, nhánh phụ dự phòng. Khi neo chính gặp sự cố, dây dự phòng đảm bảo an toàn liên tục.',
      'Dây giảm chấn Nefab, dài 1.75m, hấp thụ lực đến 400J theo ANSI Z359.13. Phù hợp công trình Mỹ/Canada có yêu cầu OSHA.',
      'Dây điều chỉnh dài 1-1.8m bằng khóa trượt trên thân dây. Tiện lợi khi cần thay đổi khoảng cách làm việc, tải 100kg.',
      'Dây cầm tay ngắn 30cm, polyester 20mm, móc inox hai đầu. Dùng giữ thăng bằng tạm thời, không phải dây chống ngã.',
      'Dây dệt thoi polyester 16mm bản rộng, dài 1.8m, mềm dẻo. Không cứng đơ trong thời tiết lạnh, dễ thao tác 2 tay.',
      'Dây hấp thụ lực 1.75m theo EN355, hộp giảm chấn loại túi xếp. Nổ hộp khi lực >6kN, giảm lực xuống còn <6kN tác động cơ thể.',
      'Dây cuộn tự thu 2m vỏ nhựa ABS nhỏ gọn 0.5kg. Ra dây khi di chuyển, thu tự động, khóa tức thì khi ngã nhanh.',
      'Dây mái nhà kép chữ Y có hộp giảm chấn mỗi nhánh. Dành cho công việc trên mái nhà, tháp truyền hình, silo.',
      'Dây chữ Y kép 1.2m mỗi nhánh, móc thép mạ kẽm 25kN. Tổng chiều dài khi mở 2.7m kể hộp giảm chấn. CE/PPE Cat.III.',
      'Dây cấu trúc thép lõi polyester bọc vỏ PVC 1m, tải 3000kg. Dùng trong ngành xây dựng cầu đường, lắp máy công nghiệp.',
      'Dây thoát hiểm cuộn tự động cho sàn cao tầng, cuộn 25m. Bộ hãm ly tâm giới hạn tốc độ 1.5m/s, không cần thao tác tay.',
    ],
  },
  'Dây An Toàn Toàn Thân': {
    names: [
      'Đai An Toàn Toàn Thân 5 Điểm Neo EN361',
      'Bộ Đai Bảo Hộ Toàn Thân Điểm Neo Lưng-Ngực',
      'Harness Toàn Thân Chuyên Leo Cao MSA Evotech',
      'Đai An Toàn Toàn Thân Cao Su Điều Chỉnh XL',
    ],
    descs: [
      'Đai toàn thân 5 điểm: 2 vai, 2 đùi, 1 ngực. Vải dệt polyester 45mm, khóa nhanh nhựa Acetal cao cấp. Điểm neo lưng 2 móc, tải 150kg, EN361.',
      'Đai toàn thân với 2 điểm neo lưng và ngực độc lập. Polyester 50mm chịu mài mòn, đệm xốp vai-đùi giảm áp. Size S đến XXL.',
      'Harness MSA Evotech Pro điều chỉnh 6 điểm, kết nối dây lưng/ngực. Nhẹ 1.2kg, thông gió lưng và vai, dùng leo ăng-ten, tháp cao.',
      'Đai toàn thân dây polyester 45mm, điều chỉnh vô cấp tất cả các đoạn. Phù hợp vòng eo 75-135cm, 5 điểm neo, kèm túi đựng.',
    ],
  },
  'Dây thắt lưng bảo vệ Security': {
    names: [
      'Thắt Lưng Bảo Vệ Da Bò Khóa Bản Rộng 4cm',
    ],
    descs: [
      'Thắt lưng da bò cao cấp dày 4mm, rộng 4cm. Khóa hợp kim kẽm mạ bạc bền đẹp, có thể gắn thêm pouche đựng dụng cụ bảo vệ.',
    ],
  },
  'Gang tay bảo hộ': {
    names: [
      'Găng Tay Sợi Len Chấm Cao Su Chống Trượt 10 Gauge',
      'Găng Tay Cao Su Chống Hóa Chất Dày 0.5mm Màu Vàng',
      'Găng Tay Da Hàn Dài 35cm Chịu Nhiệt 800°C',
      'Găng Tay Nitrile Dùng Một Lần Không Bột 100 Cái',
      'Găng Tay Cơ Học Chống Cắt Cấp Độ 5 Spandex',
      'Găng Tay Bảo Hộ Vải Canvas Lòng Bàn Tay Da Beo',
      'Găng Tay Chịu Nhiệt Silicat Lò Nung 500°C',
      'Găng Tay PVC Tráng Nhúng Toàn Bộ Lòng Bàn Tay',
      'Găng Tay Chống Điện 1000V Latex Đỏ Chuẩn IEC',
      'Găng Tay Chống Rung Bàn Tay Gel Silicon Xe Máy',
      'Găng Tay Sợi Thủy Tinh Bảo Vệ Thợ Hàn Nhiệt',
      'Găng Tay Latex Mỏng Dùng Phòng Sạch ISO 5',
      'Găng Tay Vải Terry Lòng Bàn Da Đôi Lớp Hàn Xì',
      'Găng Tay Chống Cắt HPPE Cấp F Chuẩn EN388',
      'Găng Tay Neoprene Dài 45cm Chống Dầu Acid',
      'Găng Tay Polyurethane PU Mỏng Nhẹ Lắp Ráp Điện Tử',
      'Găng Tay Cổ Tay Thun Dệt Kim Chấm Nhựa Bao Tay',
      'Găng Tay Da Hươu Cao Cổ Thợ Sắt Rèn',
      'Găng Tay Nhựa Tổng Hợp Vải 2 Mặt Thợ Cơ Khí',
      'Găng Tay Chống Nước Có Lót Flannel Giữ Ấm',
      'Găng Tay Kevlar Chống Cắt Cấp E Mỏng Nhẹ',
      'Găng Tay Thông Minh Cảm Ứng Màn Hình An Toàn',
      'Găng Tay Da Tổng Hợp Kỹ Thuật Số Lắp Ráp Nhẹ',
      'Găng Tay Sợi Tre Kháng Khuẩn Chịu Nhiệt Nhẹ',
      'Găng Tay Latex Dày 0.4mm Gia Dụng Phòng Bếp',
      'Găng Tay Bảo Hộ Vải Nhiều Lớp Hàn Xì MIG TIG',
      'Găng Tay Nylon Tráng Latex Lòng Bàn Tay Full',
    ],
    descs: [
      'Găng tay len 10 gauge đan dày, lòng bàn tay chấm cao su tự nhiên 0.5mm. Chống trượt khi cầm nắm ướt, thoáng khí, phù hợp cơ khí nhẹ.',
      'Găng cao su vàng dày 0.5mm, chịu acid HCl 30%, NaOH 50%, dầu mỡ. Dài 30cm bảo vệ cổ tay, bên trong có talc chống dính.',
      'Găng hàn da bò tự nhiên dày 2mm, lòng bàn tay đôi lớp. Dài 35cm bảo vệ cổ tay khỏi tia lửa hàn, chịu nhiệt bức xạ 800°C.',
      'Găng tay Nitrile 4 mil không bột, 100 chiếc/hộp. Không gây dị ứng latex, chống hóa chất nhẹ, dùng trong y tế và công nghiệp sạch.',
      'Găng cơ học cấp độ chống cắt 5 (EN388), Spandex 4 chiều co giãn. Mỏng 0.6mm, cảm giác chạm tốt, lắp ráp chi tiết nhỏ.',
      'Găng canvas thô lòng da beo phân mảnh, ôm khít bàn tay. Thoáng khí, thấm mồ hôi, phù hợp làm vườn, xây dựng nhẹ.',
      'Găng silicat amiăng không 500°C, dày 8mm, dài 30cm. Dùng bốc vật nóng từ lò nung, đúc kim loại, chịu tia lửa trực tiếp.',
      'Găng PVC nhúng lòng bàn tay toàn bộ màu xanh, nền vải dệt cotton. Chống dầu, nhớt, chất lỏng thông thường, grip tốt khi ướt.',
      'Găng chống điện latex đỏ 1000V AC / 1500V DC, đạt IEC 60903 Class 0. Kiểm tra hàng năm bắt buộc, bảo quản trong túi vải đen.',
      'Găng chống rung gel silicon lòng và ngón tay, co giãn 4 chiều. Dùng vận hành máy khoan, búa khí nén, giảm chấn rung 80%.',
      'Găng sợi thủy tinh bện 3 lớp, dày 4mm, chịu nhiệt 250°C liên tục. Không cháy, không dẫn điện, dùng lò hơi, đúc thủy tinh.',
      'Găng latex siêu mỏng 0.1mm ESD, phòng sạch ISO 5-7. Chống tĩnh điện <1x10⁸ Ω, bề mặt nhẵn không để lại dấu vân tay.',
      'Găng terry vải vòng lòng da đôi lớp, hàn xì MIG/TIG. Hấp thụ nhiệt tốt, bảo vệ khớp ngón, cổ tay. Kích cỡ M/L/XL.',
      'Găng HPPE cấp độ chống cắt F (EN388 4X43F), dày 1.2mm. Kết hợp sợi thủy tinh và polyester, mỏng nhẹ phù hợp thao tác nhanh.',
      'Găng Neoprene dài 45cm, dày 0.8mm. Chống acid H₂SO₄ 50%, dầu động cơ, dung môi. Tấm lót cotton thoáng khí bên trong.',
      'Găng PU mỏng 0.4mm, nền Nylon 13 gauge, cổ tay co giãn thun. Lắp ráp điện tử, kiểm tra linh kiện, thao tác chính xác cao.',
      'Găng dệt kim cổ tay thun co dãn, bề mặt chấm nhựa PU nhỏ. Chống trượt khi cầm hộp, bê đồ, phù hợp kho vận logistics.',
      'Găng da hươu cổ tay cao 15cm, thợ rèn sắt thép. Da mềm mịn, chịu nhiệt bức xạ, thoáng khí, bảo vệ cổ tay khỏi tàn tro.',
      'Găng vải 2 mặt: mặt trên canvas, mặt dưới da tổng hợp. Cơ khí, sửa xe, xây dựng, lòng bàn tay ôm chặt chi tiết máy.',
      'Găng chống nước neoprene bên ngoài, lót flannel giữ ấm bên trong. Dùng mùa đông, rửa xe ngoài trời, -20°C đến 40°C.',
      'Găng Kevlar 13 gauge cấp cắt E mỏng 0.8mm. Siêu nhẹ 40g/đôi, cảm ứng màn hình cảm ứng điện dung được. EN388 4X44E.',
      'Găng bảo hộ ngón đặc biệt tương thích màn hình cảm ứng. Neoprene + Spandex, cổ tay thun, dùng trong kho vận dùng máy tính bảng.',
      'Găng da tổng hợp nhẹ 80g/đôi, mặt lưng lỗ thoáng khí. Đường may ngoài không tạo áp điểm, phù hợp kiểm soát chất lượng.',
      'Găng sợi tre 60%, polyester 40%, kháng khuẩn tự nhiên. Hút ẩm tốt, mùa hè thoáng mát, dùng làm vườn, phân loại rác.',
      'Găng latex gia dụng 0.4mm màu hồng/vàng, dài 30cm. Dùng rửa chén, dọn vệ sinh, bảo vệ da tay khỏi hóa chất tẩy rửa.',
      'Găng hàn xì MIG/TIG da bò dày 2.5mm, nhiều lớp. Kết nối đường may inox chịu tia lửa, bảo vệ đến cổ tay 20cm.',
      'Găng Nylon 13 gauge tráng latex lòng toàn bộ màu cam. Cân bằng giữa khéo léo và bảo vệ, sắp xếp hàng hóa trong kho.',
    ],
  },
  'Giày bảo hộ lao động': {
    names: [
      'Giày Bảo Hộ Mũi Thép Đế PVC Chống Đâm Xuyên',
      'Giày Safety Jogger Bestrun S3 Mũi Composite',
      'Giày Công Trường Da Bò Mũi Thép Chuẩn EN ISO 20345',
      'Giày Chống Tĩnh Điện ESD Mũi Thép Cho Phòng Sạch',
      'Giày Chống Thấm Nước Gore-Tex Mũi Thép Rừng Núi',
      'Giày Bảo Hộ Cổ Cao Chống Trơn Trượt Dầu Nhớt',
      'Giày Hàn Cổ Cao Chịu Nhiệt Phản Xạ Mũi Thép',
      'Giày Da Bảo Hộ Nhẹ Nylon Composite Toe SRC',
      'Giày Safety Siêu Nhẹ EVA Foam Composite Toe',
      'Giày Công Nghiệp Chống Hóa Chất PU/PVC Mũi Thép',
      'Giày Bảo Hộ Cổ Thấp Lót Thép S1P Chống Xuyên',
      'Giày Sneaker Bảo Hộ Mũi Composite Trẻ Trung',
      'Giày Bảo Hộ Chống Nước Rubber Mũi Thép Xây Dựng',
      'Giày An Toàn Chống Điện 20kV Lớp Bảo Vệ Điện',
    ],
    descs: [
      'Giày da bò mũi thép đúc liền, đế PVC chống đâm xuyên lót thép. Chịu lực va 200J, nén 15kN. EN ISO 20345:2011 S1P. Size 38-46.',
      'Safety Jogger Bestrun S3 composite toe 200J, không kim loại. Lót thép SRC chống trơn dầu/nước, lót chân ESD, Gore-Tex không thấm nước.',
      'Da bò full grain tự nhiên mũi thép 200J va chạm. Đế PU/cao su chống trơn dầu cấp độ SRA+SRB, chịu nhiệt 300°C 1 phút.',
      'Giày ESD mũi thép, điện trở 100kΩ-100MΩ. Chống tĩnh điện trong phòng sạch, vùng nổ. Kèm kết quả kiểm tra điện trở từng đôi.',
      'Mũi thép 200J, màng Gore-Tex chống thấm tuyệt đối, thoáng hơi. Đế Vibram chống bùn-đá-dốc, phù hợp lâm nghiệp, khảo sát địa hình.',
      'Cổ cao 15cm chống xoắn cổ chân, da nubuck chống nước. Đế Rubber SRC chống dầu-nước, chông không trơn trên sàn kho ướt.',
      'Cổ cao hàn xì, mũi thép 200J, mặt da chịu tia lửa phản xạ. Đế cao su chịu nhiệt 300°C, không nứt gần hồ quang hàn.',
      'Da nubuck kết hợp lưới Nylon nhẹ, mũi Composite không kim loại. Siêu nhẹ 700g/đôi, phù hợp sân bay, khu vực MRI bệnh viện.',
      'Đế giữa EVA siêu nhẹ, mũi Composite 200J, tổng trọng lượng 500g/đôi. Amortized lót chân Memory Foam giảm mệt khi đứng 8h.',
      'PU bề mặt chống hóa chất acid-kiềm loãng, mũi thép 200J. Đế PVC dày chống đâm xuyên, thường dùng phòng lab, xưởng mạ.',
      'Cổ thấp S1P không yêu cầu môi trường ướt, nhưng mũi thép 200J + lót thép. Đế PU nhẹ, đường may ngoài chịu mài mòn.',
      'Kiểu dáng Sneaker hiện đại, mũi composite trong suốt không thấy. Đế cao su ngoài, SRA, chống trơn dầu ăn, phù hợp nhà hàng, bếp.',
      'Vải Rubber phủ toàn bộ ngoài chống mưa, mũi thép 200J. Đế cao su chẹn sâu chống trơn bùn đất, phù hợp công trình ngoài trời.',
      'Da bò toàn phần, mũi thép 200J, đế cách điện 20kV theo IEC 60745. Màu vàng cảnh báo điện, dùng thợ điện hạ thế.',
    ],
  },
  'Giày da bảo vệ - Có buộc dây': {
    names: [
      'Giày Da Đen Bóng Buộc Dây Bảo Vệ Oxford',
      'Giày Lính Bảo Vệ Da Tổng Hợp Buộc Dây Cao Cổ',
      'Giày Da Thật Bảo Vệ Buộc Dây Cổ Thấp Formal',
      'Giày Tuần Tra Bảo Vệ Da Bò Lót Mềm Buộc Dây',
    ],
    descs: [
      'Giày Oxford da bò thật đánh bóng, mũi tròn, đế cao su chống trơn. Đường may chỉ nâu thanh lịch, phù hợp đồng phục bảo vệ, nghi lễ.',
      'Giày cao cổ 15cm lính/bảo vệ, da tổng hợp PU chống nước. Buộc dây 8 mắt, đế lính cao su chống mài mòn, phù hợp tuần tra ngoài trời.',
      'Giày cổ thấp da thật 1.8mm, mũi vuông formal, đế PU siêu nhẹ. Buộc dây 5 mắt, dành cho bảo vệ văn phòng, tòa nhà, ngân hàng.',
      'Giày tuần tra da bò full grain 2mm, lót da êm chân. Buộc dây 7 mắt, đế cao su Goodyear welt bền lâu, có thể đóng đế lại.',
    ],
  },
  'Giày da bảo vệ - Không buộc dây': {
    names: [
      'Giày Da Lười Slip-On Bảo Vệ Khóa Velcro',
    ],
    descs: [
      'Giày da lười không dây, khóa Velcro 2 quai cho bảo vệ cao tuổi. Da tổng hợp mềm, đế cao su chống trơn, dễ mang tháo nhanh.',
    ],
  },
  'Gậy cao su - Dùi cui bảo vệ': {
    names: [
      'Dùi Cui Cao Su Đặc Chống Bạo Loạn 60cm',
    ],
    descs: [
      'Dùi cui cao su lưu hóa cứng đặc 60cm, đường kính 3.5cm. Cán thép lõi chịu lực, vỏ cao su bao ngoài an toàn. Dùng trong bảo vệ chuyên nghiệp.',
    ],
  },
  'Gậy giao thông': {
    names: [
      'Gậy Đèn LED Chỉ Hướng Giao Thông Đỏ-Xanh',
    ],
    descs: [
      'Gậy chỉ hướng 2 màu LED đỏ-xanh, đường kính 6cm, dài 50cm. Pin AA 3 cái, hoạt động 20h, nhìn rõ 200m, dùng điều phối giao thông ban đêm.',
    ],
  },
  'Hệ Thống Báo Cháy': {
    names: [
      'Đầu Báo Khói Quang Học Địa Chỉ Hóa Phân Tán',
      'Đầu Báo Nhiệt Tốc Độ Tăng Nhật Nhiệt 68°C',
      'Tủ Trung Tâm Báo Cháy 4 Zone Addressable',
      'Còi-Đèn Báo Cháy Kết Hợp Âm Lượng 110dB',
      'Nút Ấn Khẩn Cấp Báo Cháy Bằng Tay Phá Kính',
      'Module Giám Sát Đường Dây Phòng Cháy 24VDC',
      'Đầu Báo Lửa Hồng Ngoại UV Phát Hiện Ngọn Lửa',
      'Pin Backup 12V 7Ah Hệ Thống Báo Cháy Dự Phòng',
      'Cáp Chống Cháy Fire Rated LSZH 2x1.5mm² Đỏ',
      'Đầu Phun Sprinkler Xuống Dọng Zincaloy 68°C',
      'Bơm Chữa Cháy Ly Tâm Inox 3HP Hệ Áp Lực',
      'Van Báo Động Nước Sprinkler Alarm Check Valve',
      'Đồng Hồ Đo Áp Suất Hệ Thống PCCC 0-16 Bar',
      'Bình Khí CO2 MT5 Chữa Cháy 5kg Chuẩn TCVN',
    ],
    descs: [
      'Đầu báo khói quang học địa chỉ, phát hiện khói tán xạ mật độ >3%/m. Địa chỉ 1-127 trên vòng lặp, LED chỉ thị đỏ, cắm cơ sở rút được.',
      'Đầu báo nhiệt nhật nhiệt 68°C và tốc độ tăng >9°C/phút. Địa chỉ vòng lặp, thân trắng, đế tháo lắp nhanh, EN 54-5 Class A1R.',
      'Tủ trung tâm 4 zone thông thường hoặc 4 vòng lặp địa chỉ. Màn hình LCD tiếng Việt, 2 nguồn AC+DC dự phòng 24h, cổng RS232/485.',
      'Còi đèn 2 trong 1, âm lượng 110dB tại 1m, đèn Strobe 15Hz. Vỏ nhựa ABS chống bụi IP65, 24VDC, dùng ngoài trời và trong nhà.',
      'Nút ấn khẩn phá kính màu đỏ, kính nhựa dễ vỡ. Cầu tự động sau khi phá, đặt lại bằng chìa riêng. Gắn tường, dây 2x1.5mm².',
      'Module 1 input-1 output giám sát thiết bị bên ngoài. Địa chỉ vòng lặp, nguồn 24VDC, phát hiện đứt/ngắn mạch, LED chỉ thị vàng.',
      'Đầu báo lửa UV+IR đôi phổ, phát hiện ngọn lửa trong 0.5s. Góc nhìn 90°, khoảng 30m, phù hợp nhà máy sơn, kho xăng dầu.',
      'Pin chì-axit khô 12V 7Ah không tràn, nạp 10-14h đầy. Backup tủ báo cháy 12-24h khi mất điện lưới theo TCVN 3890:2009.',
      'Cáp LSZH 2x1.5mm² màu đỏ nhận biết PCCC. Chịu nhiệt 750°C/3h (FE180), vỏ Zero Halogen, tiêu chuẩn IEC 60331.',
      'Đầu phun sprinkler xuống dọng Zincaloy 68°C, K-factor 80. Độ che phủ 9m², chịu áp 1.2-12 bar, đầu phun ra tán hình nón.',
      'Bơm chữa cháy inox 3HP, lưu lượng 500L/phút tại 4 bar. Động cơ điện 3 pha 380V, chống nước IP55, đi kèm khớp nối hút và đẩy.',
      'Van báo động check valve 4" DN100, cánh van inox, phao báo áp. Kết nối chuông/còi thủy lực khi có nước chảy qua van.',
      'Đồng hồ đo áp suất 0-16 bar, mặt kính 100mm, vỏ inox 316. Chính xác 1.6%, glycerin giảm rung, kết nối 1/2" NPT nam.',
      'Bình CO2 MT5 5kg vỏ thép sơn đỏ, van đồng. Áp suất làm việc 60 bar, kiểm định 5 năm/lần theo QCVN 4:2009/BLĐTBXH.',
    ],
  },
  'Kính bảo hộ & Khẩu trang': {
    names: [
      'Kính Bảo Hộ Phủ Chống Sương Mờ Anti-Fog UV400',
      'Kính Che Mặt Toàn Phần Poly-carbon Chống Va Đập',
      'Khẩu Trang N95 FFP2 Chống Bụi Mịn PM2.5',
      'Kính Phòng Lab Chống Hóa Chất Bắn Vào Mắt',
      'Khẩu Trang Silicone Tái Sử Dụng Bộ Lọc P100',
      'Kính Hàn Tối Kính Lọc DIN 11 Chống Tia Hồ Quang',
      'Khẩu Trang Vải 3 Lớp Kháng Khuẩn Ag+ Nano Silver',
      'Kính Chống Tia UV Laser Bảo Vệ Mắt Thợ Cắt Laser',
      'Khẩu Trang Nửa Mặt Rubber Bộ Lọc Hữu Cơ A1',
      'Kính Bảo Hộ Gắn Đầu Dạng Kính Hiển Vi Zoom 3x',
      'Khẩu Trang Giấy KN95 Dây Đeo Có Kẹp Mũi',
      'Kính Cài Mũ Bảo Hiểm Trong Suốt Công Trường',
      'Khẩu Trang Hơi Clo Bộ Lọc Kép E2P3 Đầy Mặt',
      'Kính Bảo Hộ Vàng Kỳ Chống Chói Phẫu Thuật Laser',
      'Khẩu Trang Vải Kháng Khuẩn Hoạt Tính Than Bamboo',
      'Kính Bảo Hộ Kiểu Thể Thao Bảo Vệ Bên Hông',
      'Khẩu Trang PAPR Máy Thổi Khí Sạch Mũ Trùm Đầu',
      'Kính Bảo Hộ Tối Màu Chống Cường Độ Sáng UV+IR',
      'Khẩu Trang Nước Xây Dựng KN100 Bộ Lọc P3',
      'Khẩu Trang Silicone Toàn Mặt Hai Bộ Lọc A2B2P3',
    ],
    descs: [
      'Polycarbonate trong suốt, phủ Anti-Fog cả trong ngoài, UV400. Gọng nhựa dẻo ôm mặt, thoáng khí cạnh, lọc 99.9% UV. ANSI Z87.1.',
      'Tấm che polycarbonate 1.5mm full-face, lưỡi trai điều chỉnh cao-thấp. Chống va đập 120J, chống hóa chất bắn. EN 166:2002 4BT.',
      'Khẩu trang N95/FFP2, lọc ≥95% hạt 0.3µm, thở dễ. Van thở 1 chiều giảm nhiệt ẩm, dây đeo đôi chéo sau đầu. CE/FDA.',
      'Kính goggles 4 bên kín, polycarbonate 2mm chịu axit loãng. Thông gió gián tiếp chống mờ, dây đàn hồi đeo dưới cằm.',
      'Mặt nạ silicone nửa mặt, bộ lọc P100 lọc 99.97% hạt. Dây kép chỉnh được, van thở 2 bên, tái dùng 200h, bộ lọc thay riêng.',
      'Kính hàn tối màu DIN 11 lọc tia hồ quang điện. Polycarbonate 2mm, đế nâu xanh chống chói, đơn hoặc cài vào mũ hàn.',
      'Khẩu trang 3 lớp: ngoài polyester, giữa Ag+ nano diệt khuẩn, trong cotton mềm. Rửa được 50 lần, dây tai co giãn. Size M/L.',
      'Kính lọc laser bước sóng 800-1100nm, OD≥5, khung titan nhẹ. Dùng máy cắt laser fiber/CO2, bảo vệ võng mạc khỏi tia laser.',
      'Mặt nạ nửa mặt rubber dẻo, 2 bộ lọc hữu cơ A1 loại I. Lọc hơi sơn, dung môi, đến nồng độ 1000ppm. Bộ lọc thay sau 40h.',
      'Kính đeo đầu dạng loupe 3x, trường nhìn 90mm, tầm xa điều chỉnh 35-45cm. Phẫu thuật, điện tử, đồng hồ, thêu bướm, nữ trang.',
      'KN95 dây đeo cong ôm cằm, kẹp mũi nhôm điều chỉnh. 5 lớp melt-blown, lọc ≥95% hạt NaCl 0.075µm. GB 2626-2019.',
      'Kính cài vành mũ bảo hiểm trắng, gọng inox, kinh polycarbonate 2mm. Lật lên lật xuống dễ dàng, dùng công trường, mài kim loại.',
      'Mặt nạ toàn mặt silicone với bộ lọc kép E2P3 (hơi clo+bụi). Lọc khí Cl₂ đến 2000ppm, P3 lọc 99.97% hạt. EN 136:1998.',
      'Kính laser vàng OD5+ bước sóng 190-540nm, UV+xanh lục. Khung nhẹ 28g, polycarbonate tráng phủ, dùng phòng phẫu thuật laser.',
      'Khẩu trang than hoạt tính tre, 4 lớp, lọc khí độc nhẹ và bụi. Có túi than ở giữa thay được, kháng khuẩn tự nhiên, thoáng khí.',
      'Kính thể thao ôm mặt, che chắn 3 mặt bên. Polycarbonate 2mm ANSI Z87.1, tia UV400, mắt kính thay được. Phù hợp công trình ngoài trời.',
      'Mặt nạ PAPR gắn pin, quạt thổi 170L/phút qua bộ lọc HE. Mũ trùm đầu vô trùng dùng môi trường hạt phóng xạ, bệnh viện cách ly.',
      'Kính tối màu amber DIN 5, lọc 85% UV+IR. Dùng cắt plasma, hàn oxy-axetylene nhẹ, mài đá nhân tạo. ANSI Z87.1 kèm chứng chỉ.',
      'Mặt nạ nước half-face cao su, bộ lọc P3 loại III. Lọc xi-măng, bột đá cẩm thạch, silic >99.97%. Dùng thợ bê tông, mài đá.',
      'Mặt nạ silicone toàn mặt đôi bộ lọc A2B2P3 kiểu cột sơn. Lọc hơi hữu cơ, vô cơ, bụi PM0.3. Dùng phòng sơn công nghiệp.',
    ],
  },
  'Mũ bảo hộ lao động': {
    names: [
      'Mũ Bảo Hộ ABS Kiểu Châu Âu Có Rãnh Thông Gió',
      'Mũ Cứng Công Trường PE Điều Chỉnh Nhanh 6 Điểm',
      'Mũ Bảo Hộ Điện 20kV Cách Điện HDPE',
      'Mũ Bảo Hộ Vành Rộng Chống Mưa Nắng Kho Lạnh',
      'Mũ Cứng ABS Tích Hợp Kính Che Mặt Và Che Tai',
      'Mũ Bảo Hộ LED Tích Hợp Đèn Trán Sạc USB',
      'Mũ Bảo Hộ Thông Gió Nón Phẫu Thuật Xây Dựng',
      'Mũ Cứng Màu Vàng Ratchet 4 Điểm Treo Lưới',
      'Mũ Bảo Hộ Chịu Nhiệt 150°C Môi Trường Nóng',
      'Mũ Bảo Hộ Leo Cao Hai Móc Thắng Kép Kiểu Kín',
      'Mũ Cứng Kiểu Nhật Có Vành Trước Bảo Vệ Gáy',
      'Mũ Bảo Hộ ABS Khóa Xoay Bánh Răng Chống Trôi',
    ],
    descs: [
      'Mũ ABS nhựa kỹ thuật kiểu châu Âu, 8 rãnh thông gió nóc. Vành 30mm bảo vệ mưa nắng, dây đeo 4 điểm nylon, kèm dây cằm.',
      'Mũ PE cứng, khóa nhanh xoay bánh răng ±5 cỡ đầu 52-62cm. Dây treo 6 điểm thoáng khí, lót mồ hôi tháo giặt được. EN 397.',
      'Mũ HDPE cách điện 20kV AC theo EN 50365. Màu vàng/đỏ, vành 30mm bảo vệ mưa, không chứa kim loại, thợ điện hạ thế.',
      'Vành rộng 70mm xung quanh che mưa nắng, phù hợp làm ngoài trời. PE cứng, dây treo 4 điểm, dùng kho lạnh -20°C đến +50°C.',
      'Hệ 3 trong 1: mũ cứng + kính che mặt polycarbonate + nút tai chống ồn. Kính lật lên xuống, tai lật ra vào, EN 397+EN 1731.',
      'Mũ ABS tích hợp đèn LED trán sạc USB Type-C, pin 1200mAh. Sáng 3 chế độ 80-200 lux, dây đeo cao su đầu, tự tắt sau 2h.',
      'Nón thông gió 6 lỗ nóc + 2 bên, ABS nhẹ 350g. Dây treo thoáng, lót mồ hôi kháng khuẩn, phù hợp làm việc trong nhà nóng.',
      'Mũ PE màu vàng, 4 điểm treo lưới PE thoáng khí. Khóa xoay nhanh 1 tay, vành trước 20mm, dây cằm V dễ điều chỉnh.',
      'Mũ ABS chịu nhiệt 150°C ngắn hạn, 80°C liên tục. Dùng lò hơi, lò nung, sản xuất kính, nhà máy xi-măng. EN 397 HT.',
      'Mũ kín kiểu leo núi/leo cao, 2 móc thắng kép bên tai. Bề mặt ABS nhám, cằm buộc chắc, kèm núm tai silicon giảm ồn.',
      'Kiểu mũ Nhật vành ngắn trước, rộng sau che gáy. ABS nhẹ, lỗ thông gió 4 bên, móc đèn trán tích hợp, dây 4 điểm.',
      'Khóa xoay bánh răng chính xác, không trôi khi đập đầu vào vật. ABS cứng màu trắng, vành 25mm, dùng xây dựng và khai thác mỏ.',
    ],
  },
  'Mặt nạ hàn bảo hộ lao động': {
    names: [
      'Mặt Nạ Hàn Tự Động Tối Màu Điện Tử Solar ADF',
      'Mặt Nạ Hàn Kính Tối DIN 11 Truyền Thống Nylon',
      'Mặt Nạ Hàn Vành Đầu Điều Chỉnh Kính Lọc Đổi',
      'Mặt Nạ Hàn Tự Động 4 Cảm Biến DIN 9-13 ANSI',
      'Mặt Nạ Hàn MIG/TIG/Cắt Plasma Kính Solar Large',
      'Kính Hàn Tay Cầm Polycarbonate Kính Tối DIN 12',
      'Mặt Nạ Hàn Tự Tối LED Đa Chức Năng Cơ Sở Đầu',
      'Mặt Nạ Hàn Nặng Chịu Lực Fiberglass Kính DIN 11',
    ],
    descs: [
      'Kính Solar+Lithium, tự tối trong 1/25000s, tự sáng 0.5s. DIN 9-13 điều chỉnh, nhạy sáng 1-4, độ trễ 0.1-1s. 4 cảm biến hồ quang.',
      'Mặt nạ nylon nhẹ, kính lọc thủy tinh tối DIN 11, kích thước 90x110mm. Vành đầu nhựa điều chỉnh 3 cỡ, chống tia UV/IR/hồ quang.',
      'Vành đầu ratchet 4 điểm, kính lọc thay được 90x110mm DIN 9-12. Bản lề lật tấm kính lên 90° khi không hàn, tấm trong bảo vệ.',
      'Mặt nạ 4 cảm biến quang điện, DIN 9-13 xoay số, nhạy sáng điều chỉnh. Màn Crystal View 97x40mm, pin solar+AA, ANSI Z87.1.',
      'Kính che rộng 110x90mm cho MIG/TIG/cắt plasma, solar 2 pin. DIN 9-13 nút xoay ngoài, trả về DIN 4 ánh sáng thường, CE EN 379.',
      'Kính hàn tay cầm nhựa, polycarbonate trong + tấm kính DIN 12 đặt vào. Dùng hàn điện hồ quang ngắn, tấm kính thay theo tiêu chuẩn.',
      'Mặt nạ tự tối LED hỗ trợ nhìn rõ vũng hàn hơn. Solar+CR2032, DIN 5-13 điều chỉnh, mặt nhìn 98x43mm, ANSI Z87.1 tại Mỹ.',
      'Thân mặt nạ sợi thủy tinh cao cấp, chịu bắn kim loại nóng. Kính DIN 11 thủy tinh, kèm 2 tấm trong, bản lề dày 2mm không gỉ.',
    ],
  },
  'Mặt Nạ Phòng Độc': {
    names: [
      'Mặt Nạ Phòng Độc Toàn Mặt Bộ Lọc ABEK1P3',
      'Mặt Nạ Nửa Mặt Cao Su Bộ Lọc Hữu Cơ A2B2',
      'Mặt Nạ Phòng Độc Khí Độc Hóa Học CBRN Quân Sự',
      'Bộ Lọc Thay Thế Mặt Nạ Phòng Độc A1B1E1K1P3',
      'Mặt Nạ Phòng Độc Vô Cơ E1P2 Hơi Amoniac',
      'Mặt Nạ Hóa Chất Toàn Mặt Butyrate Rubber CSA',
      'Mặt Nạ Phòng Độc Silicone Toàn Mặt Lọc Kép',
      'Mặt Nạ Phòng Thủ Hóa Học Với Ống Thở Thoát Hiểm',
      'Bộ Lọc Bụi P100 Mặt Nạ Phòng Độc 40mm',
      'Mặt Nạ Phòng Độc Khẩn Cấp Thoát Hiểm EEBD 15 Phút',
      'Mặt Nạ Phòng Thủ Hơi Amoniac NH3 Nông Nghiệp',
      'Bộ Mặt Nạ Phòng Độc NBC Tích Hợp Kính Nhìn Rộng',
      'Mặt Nạ Phòng Độc Hở Phần Mặt Chỉ Che Mũi-Miệng',
      'Mặt Nạ Phòng Độc Sơn Bộ Lọc OV/P100 Nửa Mặt',
      'Bộ Lọc Phòng Độc Thủy Ngân Hơi Hg HgP3',
    ],
    descs: [
      'Mặt nạ silicon toàn mặt 2 bộ lọc ABEK1P3, chống hữu cơ, vô cơ, axit, NH3, bụi. Trọng lượng 700g, dây đeo 5 điểm, kính polycarbonate EN 136.',
      'Nửa mặt cao su neoprene, 1 bộ lọc A2B2 hữu cơ+vô cơ. Lọc dung môi, chlorine, SO₂. Dây cổ+đầu, van thở 1 chiều, EN 140.',
      'Mặt nạ quân sự M40/M50 chuẩn CBRN, lọc vũ khí hóa học thần kinh, nổ. Mặt kính toàn diện, bộ lọc NATO 40mm, tẩy độc bằng dung dịch DS2.',
      'Bộ lọc A1B1E1K1P3 chuyên dụng lọc hơi hữu cơ, vô cơ, axit, NH3. Kết nối 40mm chuẩn NATO, dùng được trên mọi mặt nạ 40mm phổ biến.',
      'Bộ lọc E1P2 chuyên hơi SO₂, NO₂, amoniac nồng độ thấp. Dùng nhà máy hóa chất, phân bón, làm lạnh. Thay sau 40h hoặc có mùi.',
      'Butyrate rubber chịu hóa chất mạnh hơn silicone. Toàn mặt, cổng 40mm, kính Lexan polycarbonate 3mm. CSA Z180.1, NIOSH phê duyệt.',
      'Silicone toàn mặt với 2 bộ lọc đặt hai bên tăng tầm nhìn. Lọc ABEK2P3, dây 6 điểm siết chặt, kính 4 cạnh tầm nhìn rộng.',
      'Mặt nạ thoát hiểm có ống thở và bộ lọc phổ rộng, đeo nhanh 5 giây. Sử dụng 15-20 phút trong tình huống khẩn cấp lửa/khí độc.',
      'Bộ lọc P100 40mm lọc 99.97% hạt bụi, mịn, sợi amiăng. Gắn mặt nạ 40mm chuẩn NATO, trọng lượng 100g, thay sau 200h.',
      'EEBD (Emergency Escape Breathing Device) 15 phút O2 áp. Đeo nhanh không cần đào tạo, dành cho nhân viên nhà máy, tàu biển, hầm lò.',
      'Mặt nạ nửa mặt cao su, bộ lọc NH3/amoniac E2. Dùng nông nghiệp, chuồng trại, nhà máy đông lạnh làm lạnh amoniac, lưu giữ đến 1 năm.',
      'Mặt nạ toàn mặt NBC, kính nhìn rộng 180°, bộ lọc ABEK2P3. Chống vũ khí hóa học, sinh học, phóng xạ dạng hạt. Dây đeo 6 điểm kép.',
      'Mặt nạ nửa đơn giản chỉ che mũi-miệng, thoáng phần mắt. 2 bộ lọc nhỏ A1, dành cho công việc sơn, tiếp xúc dung môi nhẹ.',
      'Nửa mặt cao su, bộ lọc OV/P100 kép lọc hơi hữu cơ+bụi sơn. Dùng phòng sơn ô tô, tàu thuyền. Thay bộ lọc sau 40h làm việc.',
      'Bộ lọc thủy ngân Hg chuyên biệt, kết hợp P3 lọc hạt. Dùng phòng thí nghiệm, nhà máy ắc quy, tái chế điện tử. Thay sau 8h tiếp xúc.',
    ],
  },
  'Nón , Sao Bảo Vệ': {
    names: [
      'Nón Kết Bảo Vệ Vải Cao Cấp Logo Thêu Chính Hãng',
      'Sao Cấp Hiệu Bảo Vệ Inox Mạ Vàng 1-5 Sao',
    ],
    descs: [
      'Nón kết vải polyester cao cấp, thêu logo an ninh/bảo vệ. Vành cứng, điều chỉnh sau đầu, size 55-60cm, dùng mưa nắng không phai màu.',
      'Bộ sao cấp hiệu bảo vệ 1 đến 5 sao, hợp kim kẽm mạ vàng. Đường kính 2cm mỗi sao, kèm gắn nhọn, dễ gắn lên nón kết.',
    ],
  },
  'Nón vải lưới trùm': {
    names: [
      'Nón Vải Lưới Bảo Vệ Trùm Đầu Loại Xốp Kẹp',
      'Mũ Vải Lưới Thông Gió Nón Bảo Hộ Công Trường',
      'Nón Lưới Trong Mũ Cứng Bảo Vệ Mặt Bụi Côn Trùng',
      'Mũ Lưới Trùm Thoáng Mát Mùa Hè Xây Dựng',
    ],
    descs: [
      'Nón lưới vải PE loại xốp kẹp bên trong mũ bảo hộ cứng. Hút mồ hôi, chống nóng đầu, thay thế khi cũ dơ. Phù hợp hầu hết mũ bảo hộ cứng.',
      'Mũ vải lưới đứng tháo rời từ mũ bảo hộ, thông gió 100%. Dây điều chỉnh, co giãn, chạm đầu mềm, màu trắng/vàng, giặt máy được.',
      'Lưới vải gắn vào vành mũ cứng che mặt, cổ tránh bụi và côn trùng. Polyester thoáng, nhìn xuyên được, bấm nhanh vào vành mũ.',
      'Mũ lưới mùa hè siêu thoáng có kèm vành che nắng rộng 5cm. Polyester lưới 3D, băng trán chống mồ hôi nhỏ vào mắt, co giãn 4 chiều.',
    ],
  },
  'Nút chống ồn': {
    names: [
      'Nút Tai Silicone Mềm Chống Ồn SNR 37dB Tái Dùng',
      'Nút Tai Mút Xốp Dùng Một Lần NRR 33dB Cam Vilagrip',
      'Chụp Tai Chống Ồn Gắn Mũ SNR 28dB',
      'Nút Tai Có Dây Bọc Mút PU Xốp SNR 35dB',
      'Chụp Tai Chống Ồn Dạng Băng Đầu Foldable NRR 30dB',
      'Nút Tai Silicone Dạng Nón 3 Tầng SNR 36dB Dây Cổ',
      'Chụp Tai Hi-Fi Chuẩn Âm Nhạc Chặn 15dB Có Chọn Lọc',
      'Bộ Nút Tai Bảo Vệ Thính Giác Kèm Hộp Đựng 50 Cặp',
    ],
    descs: [
      'Silicone y tế mềm dẻo, hình nón 3 tầng, SNR 37dB. Rửa xà phòng được, tái dùng 300 lần, phù hợp ống tai 6-14mm. CE EN 352-2.',
      'Mút PU tốc độ nở chậm, cuộn nhỏ nhét dễ, nở đầy ống tai 60s. SNR 33dB, 200 cặp/hộp, màu cam nhận biết, ANSI S3.19, EN 352-2.',
      'Chụp tai gắn ray mũ bảo hộ cứng, không cần đeo cả bộ khi chỉ cần thỉnh thoảng. SNR 28dB, gập vào mũ khi không dùng, CE EN 352-3.',
      'Mút PU có dây nối 2 nút tai, không rơi mất. SNR 35dB, dây polyester 50cm, kẹp áo khi không dùng, OSHA 1910.95 khuyến dùng.',
      'Băng đầu dạng chữ C mềm, gấp được bỏ túi. Đệm tai PU êm, NRR 30dB, màu xanh, thép lò xo không gỉ, phù hợp đội-bỏ liên tục.',
      'Silicone 3 tầng có dây cổ dài 60cm chống mất. SNR 36dB, nhét tái dùng, vệ sinh dễ, kèm hộp tròn đựng, CE EN 352-2.',
      'Chụp tai Hi-Fi giảm đều tất cả tần số (không cắt âm bass). Giảm 15-20dB, nghe âm nhạc/nói chuyện vẫn rõ, dùng hòa nhạc, quán bar.',
      'Bộ nút tai PU 50 cặp kèm hộp nhựa đựng chuyên nghiệp. SNR 33dB, màu xanh, đóng túi zip cặp đôi, dùng cho cả phân xưởng.',
    ],
  },
  'Nội quy-Tiêu đề-Cấm lửa-Cấm hút thuốc': {
    names: [
      'Biển Nội Quy An Toàn Lao Động 10 Điều Nhựa A2',
      'Biển Cấm Lửa-Không Hút Thuốc Kho Hóa Chất',
      'Bảng Tiêu Đề Phòng Ban Alu Composite Màu In',
      'Biển Cấm Hút Thuốc Khu Vực Bệnh Viện Nhựa PVC',
    ],
    descs: [
      'Biển nhựa PVC 3mm, in offset 4 màu nội quy 10 điểm chữ đậm. Kích thước A2 (42x59cm), lỗ treo 4 góc, ép film bóng chống ẩm.',
      'Biển 2 trong 1 "Cấm Lửa + Cấm Hút Thuốc" theo TCVN 4878. Nhôm 1mm in sơn đốt lò nhiệt độ cao không phai, kèm khung treo.',
      'Tấm Alu Composite 3mm khắc laser tên phòng ban, chữ nổi 3D. Màu sắc theo đặt hàng, kích thước 30x10cm, bắt vít hoặc băng keo 3M.',
      'Biển "Khu Vực Không Hút Thuốc" nhựa PVC 5mm màu xanh-trắng. Kích thước 20x30cm, phản quang ban đêm, theo Nghị định 67/2013.',
    ],
  },
  'Thang Thoát Hiểm Cuốn': {
    names: [
      'Thang Thoát Hiểm Cuộn Xích Thép Nhà Cao Tầng 6m',
      'Thang Thoát Hiểm Dây Thừng Chống Cháy 10m',
      'Thang Cuộn Inox Thoát Hiểm Chung Cư Gắn Tường 15m',
    ],
    descs: [
      'Thang xích thép mạ kẽm, bậc sắt Ø20mm, dài 6m (2 tầng). Chịu tải 150kg, gấp gọn 30x15x10cm, móc treo cửa sổ chắc chắn.',
      'Thang dây nylon chống cháy 10m, bậc nhựa chống trượt rộng 25cm. Nhẹ 2.5kg, cuộn gọn trong túi vải. Chịu tải 120kg, dùng 1-3 tầng.',
      'Thang inox 304 cuộn gắn tường, dài 15m, bậc inox 25mm tráng nhựa. Cơ cấu xả tự động khi giật tay cầm, tốc độ xuống an toàn 1m/s.',
    ],
  },
  'Thiết bị PCCC & An toàn': {
    names: [
      'Bình Chữa Cháy Bột ABC MFZ 4kg Van Đồng',
      'Bình Chữa Cháy CO2 MT3 3kg Chai Thép',
      'Hộp Đựng Bình Chữa Cháy Thép Sơn Đỏ Khóa Kính',
      'Búa Phá Cửa Kính Thoát Hiểm 2 Trong 1 Cắt Dây',
      'Đèn Thoát Hiểm Exit LED Sự Cố 1 Tiếng',
      'Mặt Nạ Thoát Hiểm Khói Lửa 15 Phút Khẩn Cấp',
      'Dây Cứu Hỏa Cao Su Đàn Hồi 20m Vòi Phun',
      'Bộ Dụng Cụ Cứu Hỏa Phá Dỡ Chuyên Nghiệp 6 Món',
      'Thùng Cát Chữa Cháy Nhựa Màu Đỏ 100 Lít Có Nắp',
      'Bảng Hướng Dẫn Thoát Hiểm Phát Sáng Dạ Quang',
      'Đèn Pin Thoát Hiểm Sạc Tự Động Từ Điện Lưới',
      'Còi Thoát Hiểm Hơi Nén Cầm Tay 120dB Chống Nước',
      'Bộ Dây Hạ Xuống Khẩn Cấp Tự Hãm Tốc Độ 20m',
      'Bộ Kit Sơ Cứu Y Tế Công Trường 50 Người OSHA',
      'Tấm Chắn Lửa Sợi Thủy Tinh 120x180cm Kho',
      'Thước Cuộn 3m Có Gắn Đèn LED Soi Hộp Điện',
    ],
    descs: [
      'Bình bột ABC 4kg, áp xuất nạp 14 bar, van đồng chịu nhiệt. Dập tắt đám cháy loại A (rắn), B (lỏng), C (khí), E (điện). QCVN 4:2009.',
      'Bình CO2 3kg chai thép, áp nạp 60 bar, van đồng. Không để lại cặn, dùng dập tắt cháy điện, trang thiết bị điện tử. Kiểm định 5 năm/lần.',
      'Hộp thép sơn đỏ epoxy, kính phá khẩn, khóa tam giác chuẩn. Kích thước phù hợp bình 4-8kg, gắn tường bằng 4 bu-lông inox.',
      'Búa phá cửa kính đầu thép cứng, cán cao su chống trượt. Tích hợp lưỡi dao cắt dây an toàn. Nhỏ gọn 15cm, móc bảng điều khiển xe.',
      'Đèn LED xanh EXIT/LỐI THOÁT, tự sáng khi mất điện. Pin Lithium sạc từ nguồn AC, sáng ≥1h sự cố, tiêu chuẩn TCVN 3890:2009.',
      'Mặt nạ hood thoát khói 15 phút, bộ lọc hạt+CO loại TH100. Đội nhanh 5 giây, bộ lọc dự phòng kèm theo, dùng cho khách sạn, văn phòng.',
      'Vòi cao su đàn hồi 20m Ø25mm, áp làm việc 12 bar, kết nối khớp nối B65 tiêu chuẩn. Dùng cho hệ thống hydrant tường/cột.',
      'Bộ cứu hỏa 6 món: rìu phá cửa, câu liêm, gậy chọc, xà beng, xẻng, búa. Thép C45 cao cấp, cán gỗ sồi, trọng lượng bộ 8kg.',
      'Thùng nhựa HDPE đỏ 100L có nắp đậy và tay xách. Đựng cát vô cơ dập tắt đám cháy loại D (kim loại), kèm xẻng gắn nắp.',
      'Bảng dạ quang phát sáng 8h sau khi hấp sáng 30 phút. Không cần điện, nhìn rõ 15m trong bóng tối hoàn toàn. Kích thước 15x40cm.',
      'Đèn pin tự sạc từ điện lưới 220V, rút ra dùng khi mất điện. Pin NiMH 1000mAh, sáng 1.5h liên tục, sạc đầy trong 8h tự ngắt.',
      'Còi hơi nén 120dB, chống nước IP67, cầm tay gọn. Dùng gọi cứu nạn trong đám cháy, thoát hiểm, báo động khẩn cấp.',
      'Bộ hạ xuống khẩn cấp 20m, cơ cấu hãm tốc độ dưới 1.5m/s. Cuộn sẵn, mở ra đầu nối trong 10 giây, tải 100kg, không cần đào tạo.',
      'Bộ sơ cứu 50 người gồm 140 vật tư theo danh sách OSHA. Hộp nhựa ABS cứng, kèm hướng dẫn tiếng Việt, treo tường đặt sẵn.',
      'Tấm chắn lửa sợi thủy tinh dệt 120x180cm, chịu 550°C liên tục. Bọc vật dễ cháy, dùng phòng sơn, gần lò hàn, kho. Viền inox.',
      'Thước cuộn 3m tích hợp đèn LED soi tối trong hộp điện. Pin CR2032, khóa chổng trả, lưỡi thép không gỉ, phù hợp thợ điện.',
    ],
  },
  'Thùng đựng rác': {
    names: [
      'Thùng Rác Nhựa HDPE 240L Có Nắp Đậy 2 Bánh',
      'Thùng Rác Phân Loại 3 Ngăn Inox Mờ Công Cộng',
      'Thùng Rác 120L Treo Xe Gom Rác Màu Vàng/Xanh',
      'Thùng Rác Đạp Chân Inox 30L Văn Phòng Cao Cấp',
      'Thùng Rác Nhựa 60L Màu Cam Thoát Nước Đáy',
      'Thùng Đựng Rác Thải Nguy Hại 200L Biohazard',
      'Thùng Rác Phân Loại Tại Nguồn 3 Màu 30L/ngăn',
      'Thùng Rác Ngoài Trời Bê Tông Đúc Sẵn 60L Công Viên',
      'Thùng Rác Nhựa 660L Container Rác Thị Trường',
      'Thùng Rác Cảm Biến Tự Mở Nắp Inox 20L USB',
      'Thùng Rác Gỗ Tự Nhiên Lát Vân Sồi Đẹp Nội Thất',
      'Thùng Rác Khu Công Nghiệp 1100L 4 Bánh Màu Xám',
    ],
    descs: [
      'Thùng HDPE 240L, nắp đậy kín tránh mùi, 2 bánh cao su 20cm. Tay cầm đôi để đổ vào xe gom rác, màu xanh/nâu/vàng phân loại.',
      'Thùng inox 304 3 ngăn phân loại: hữu cơ-vô cơ-tái chế. Mỗi ngăn 30L, pedal đạp chân, lỗ thoát khí bên hông, màu xám mờ hiện đại.',
      'Thùng nhựa 120L treo khung xe gom rác, lỗ xỏ khung tiêu chuẩn. Nắp liền thân, màu vàng (vô cơ)/xanh (tái chế) theo QCVN.',
      'Thùng inox 304 bóng 30L, đạp chân mở nắp, nắp giảm chấn êm. Đường kính 32cm cao 55cm, phù hợp văn phòng, khách sạn 4-5 sao.',
      'Thùng nhựa 60L màu cam, lỗ thoát nước đáy, tay xách 2 bên. Dùng ngoài trời, nhà bếp nhà hàng, có thể xếp chồng lên nhau.',
      'Thùng 200L màu đỏ nhãn hiệu Biohazard/Chất Thải Y Tế. HDPE nguyên sinh, nắp bướm an toàn, lỗ túi chuyên dụng, bánh lăn, CE.',
      'Bộ 3 thùng nhựa 30L/ngăn màu xanh-vàng-đỏ theo tiêu chuẩn phân loại 3 nhóm tại nguồn theo Nghị định 45/2022. Nắp liền, pedal.',
      'Thùng bê tông đúc sẵn 60L hình trụ, lõi thép chống vỡ. Bề mặt granito giả đá, không phai màu, dùng công viên, vỉa hè bền 20 năm.',
      'Container rác nhựa 660L tiêu chuẩn châu Âu, 4 bánh cao su Ø200mm. 2 bánh khóa, tay cầm đẩy, nắp phẳng dễ lật, màu xanh/xám.',
      'Thùng inox cảm biến hồng ngoại tự mở nắp trong 0.5s. 20L, USB sạc pin lithium, nhận tay từ 25cm, im lặng mờ ban đêm.',
      'Thùng gỗ tự nhiên ván ghép lát vân sồi, sơn PU chống ẩm. Lỗ bỏ rác tròn Ø20cm, lót nhựa trong, phù hợp nội thất cao cấp.',
      'Thùng nhựa 1100L màu xám 4 bánh cao su Ø250mm, 2 khóa. Dùng khu công nghiệp, chung cư lớn, giao diện xe rác cơ giới hóa.',
    ],
  },
  'Áo cá sấu mè cao cấp nhiều': {
    names: [
      'Áo Thun Cá Sấu Bảo Vệ Cotton Pique Polo Ngắn Tay',
      'Áo Polo Bảo Vệ Phối Màu Xanh Đen Logo Thêu',
      'Áo Cá Sấu Dài Tay Chuyên Nghiệp Cho Bảo Vệ',
      'Áo Polo Security Vải Cotton Mè 65/35 Phản Quang',
      'Áo Thun Cá Sấu Thoáng Mát 4 Chiều Kháng Khuẩn',
      'Áo Polo Đồng Phục Bảo Vệ Màu Trắng-Xanh Cao Cấp',
      'Áo Cá Sấu Mè Cao Cấp Cúc Nhựa Sừng Nhiều Màu',
      'Áo Polo Bảo Vệ Phối Sọc Tay Logo In Nổi',
    ],
    descs: [
      'Cotton Pique 220gsm, thêu logo bảo vệ trước ngực, cổ bẻ vải dệt kim. Co giãn nhẹ, thoáng khí, mặc làm việc cả ngày thoải mái.',
      'Áo polo 2 màu xanh đen phối đường viền tay, thêu chữ SECURITY bên tay. Cotton/Polyester 65/35, 180gsm, không bai giãn sau 50 lần giặt.',
      'Dài tay giữ ấm mùa lạnh, cotton pique 200gsm, tay phối màu. Thêu logo đỉnh ngực phải, bo tay vải thun, kèm túi ngực trái.',
      'Vải cotton mè 65/35, in dải phản quang bên hông và tay. Ban đêm nhìn rõ từ 80m, phù hợp bảo vệ tuần tra ngoài trời ban đêm.',
      'Vải poly 4 chiều co giãn kháng khuẩn Ag+, 160gsm nhẹ mát. Cổ bẻ 3 cúc, thoát ẩm tốt, màu navy/trắng/xanh rêu tùy chọn.',
      'Cotton pique cao cấp 220gsm, 2 màu trắng-xanh đồng phục ngân hàng, khách sạn. Đường may kép bền chắc, thêu logo 2 màu.',
      'Cúc nhựa sừng 3 cúc, không gỉ sét, áo mè lỗ thoáng mát. Cotton 100% 180gsm, nhiều màu sắc, tương thích đồng phục doanh nghiệp.',
      'Sọc ngang tay áo 2cm, in logo nổi 3D trước ngực. Vải mè polyester cao cấp, nhẹ 150gsm, màu trắng sọc xanh/đỏ/vàng.',
    ],
  },
  'Áo Phản Quang': {
    names: [
      'Áo Phản Quang Vàng 3 Dải EN ISO 20471 Class 2',
      'Áo Gile Phản Quang Cam Không Tay Cho Công Nhân',
      'Áo Phản Quang Dài Tay Chống Mưa Lớp Ngoài',
      'Áo Bảo Hộ Phản Quang Nhiều Túi Class 3 Xây Dựng',
      'Áo Phản Quang Nhẹ Mesh Lưới Công Trường Ngoài Trời',
      'Áo Phản Quang Thoáng Khí Cool Wick Mùa Hè',
      'Bộ Quần Áo Phản Quang Toàn Thân Class 2 Thợ Đường',
      'Áo Phản Quang Cam Phối Dải Bạc 3M Scotchlite',
      'Áo Phản Quang Vải Dù Chống Xé Rách Cường Độ Cao',
      'Áo Gile Phản Quang Điều Chỉnh Kích Cỡ Dây Kéo',
      'Áo Phản Quang Kẻ Sọc Dọc Vàng-Cam Nhiều Màu',
      'Áo Phản Quang Có Mũ Chống Mưa Kéo Khóa Toàn Bộ',
      'Áo Phản Quang Siêu Nhẹ Thoáng Cho Chạy Bộ Ban Đêm',
      'Áo Phản Quang Nhân Viên Bảo Vệ Màu Xanh In Chữ',
      'Áo Gile Phản Quang 5 Túi Thợ Điện Trước-Sau',
      'Áo Phản Quang Cho Trẻ Em Đi Học Phản Quang Cao',
      'Áo Phản Quang Thể Thao Chạy Đêm Vải Poly Nhẹ',
      'Áo Phản Quang Cảnh Sát Giao Thông Xanh 3 Dải',
      'Áo Gile Bảo Hộ Phản Quang Thợ Hàn Đặc Biệt',
      'Áo Phản Quang Kho Vận Logistics Class 2 Túi Ngực',
      'Áo Phản Quang Tích Hợp Đèn LED Chạy Ban Đêm',
      'Áo Phản Quang Vàng Chanh Class 2 Thợ Xây Dựng',
      'Áo Phản Quang Toàn Thân Áo Liền Quần Cung Đường',
      'Bộ Áo Phản Quang Đồng Bộ 2 Màu Phân Biệt Vai Trò',
      'Áo Phản Quang Mỏng Nhẹ Thoáng 100g Cực Kỳ Nhẹ',
      'Áo Phản Quang Chữ In NHÂN VIÊN KỸ THUẬT Lưng',
      'Áo Phản Quang Gile Kéo Khóa Sườn Điều Chỉnh Co Giãn',
      'Áo Phản Quang Nữ Ôm Dáng Không Lỏng Kho Vận',
      'Áo Phản Quang Nhiệt Hạch Màu Cam/Vàng Theo Yêu Cầu',
      'Áo Phản Quang Dây Kéo YKK Khóa Kim Loại Bền',
      'Áo Phản Quang Thoáng Khí 3 Dải 5cm Mềm Không Cứng',
      'Áo Gile Phản Quang Có Nút Trên Vai Thoáng Mát Nhất',
      'Áo Phản Quang Bọc Ngực Chắc Chắn Vai Rộng',
      'Áo Phản Quang Đa Năng Kết Hợp Áo Khoác Gió',
      'Áo Phản Quang Màu Xanh Biển Navy Cho Bảo Vệ',
      'Áo Phản Quang Cam Lớp Lưới Bên Trong Mát Hơn',
      'Áo Phản Quang Cổ Bo Gile Không Tay Khóa Vải',
      'Áo Phản Quang Chữ In SECURITY Phân Biệt Ngay',
      'Áo Gile Phản Quang Thêu Logo Công Ty Theo Yêu Cầu',
      'Áo Phản Quang Class 3 Tay Dài Dải Vai-Hông-Tay',
      'Áo Phản Quang Mùa Đông Lót Lông Ấm Bên Trong',
      'Áo Phản Quang 4 Túi Zip Chuyên Nghiệp Kỹ Thuật',
      'Áo Phản Quang Cảnh Báo Khẩn Cam Sáng Cường Độ Cao',
      'Áo Phản Quang Hữu Cơ Tái Chế Eco-Friendly RPET',
      'Áo Phản Quang Dạng Yếm Hai Dải Bụng Kèm Lưng',
      'Áo Phản Quang Vải Dù Oxford 600D Chắc Bền',
      'Bộ Áo Phản Quang Cho Cả Nhóm 10 Áo Đồng Nhất',
      'Áo Phản Quang Bền Hơn Dải 3M 983 Chống Mài Mòn',
      'Áo Phản Quang Có Dải Phản Quang Vai-Ngực-Hông',
      'Áo Phản Quang Thêu Tên Cá Nhân Theo Yêu Cầu',
      'Áo Gile Phản Quang Ẩm Thực Nhà Hàng Nhân Viên Phục Vụ',
      'Áo Phản Quang Công Ty In Logo Nhanh Chỉnh Sửa Được',
      'Áo Phản Quang Loại 1 Nhẹ Nhàng Chạy Xe Đạp',
      'Áo Phản Quang Nhân Viên Giao Hàng Tốc Hành',
      'Áo Phản Quang Nhân Viên Dọn Vệ Sinh Cam Đặc Biệt',
      'Áo Gile Phản Quang Lý Tưởng Cho Nhân Viên Sân Bay',
      'Áo Phản Quang Đường Sắt Đô Thị MRT Xanh Lá',
      'Áo Phản Quang Bảo Hộ Cảnh Báo Cho Lái Xe',
      'Áo Phản Quang Ngày-Đêm Cả Năm Mọi Thời Tiết',
      'Áo Phản Quang Tay Ngắn Hãy Bắt Đầu An Toàn',
      'Áo Phản Quang Vải Thun Phối Dải Thêm Ấm Mùa Lạnh',
      'Áo Phản Quang Chuyên Dụng Cho Cẩu Tháp Xây Dựng',
      'Áo Phản Quang Áo Liền Quần Thùng Thầu Công Trình',
      'Áo Phản Quang Gile Ngắn Tới Bụng Gọn Nhẹ',
    ],
    descs: [
      'Áo vàng Class 2 EN ISO 20471, 2 dải ngang thân + dải vai. Vải polyester 120gsm, dải phản quang 50mm RA≥330 cd/lux/m².',
      'Gile không tay, vải lưới 100% polyester thoáng khí, màu cam ANSI. 3 dải phản quang, khóa kéo trước, điều chỉnh hông bằng quai velcro.',
      'Áo phản quang tay dài, lớp ngoài vải dù chống mưa nhẹ PU 1000mm. 4 dải phản quang, 2 túi hông zip, dây kéo YKK bền, EN 343.',
      'Class 3 full body, 7 dải phản quang: 2 thân + 2 tay + vai chéo. 5 túi: 2 ngực, 2 hông, 1 sau lưng, vải canvas 180gsm.',
      'Lưới mesh polyester 80gsm siêu nhẹ, thoáng 100%. 2 dải phản quang 50mm, khóa trước, điều chỉnh hông, gọn nhẹ trong ba lô.',
      'Vải Cool Wick thoát ẩm nhanh, nhẹ 90gsm. Dải phản quang bạc 3M 983 bền 50 lần giặt, màu vàng huỳnh quang sáng ngay ngày nhiều mây.',
      'Bộ quần áo class 2: áo cam + quần vàng 2 dải hông-cổ chân. Đồng bộ màu phân biệt vai trò, đường may phòng lab chuyên nghiệp.',
      'Vải polyester cam, dải 3M Scotchlite 983 bạc chính hãng. RA≥550 cd/lux/m² loại 3M, bền mài mòn, 100 lần giặt vẫn sáng.',
      'Vải dù Oxford 600D chịu rách, xé không thủng, chống gió. 3 dải phản quang 50mm trên vải chắc, phù hợp công trường khắc nghiệt.',
      'Khóa kéo 2 bên hông điều chỉnh size S-XL cho 1 áo. Không cần mua nhiều size, tiết kiệm chi phí đặt hàng đồng phục nhóm.',
      'Kẻ sọc dọc vàng-cam 2.5cm xen kẽ, tạo hiệu ứng phản quang cả hai màu. Hiển thị tốt hơn khi nhìn ngang, phù hợp cảnh báo đường bộ.',
      'Mũ liền áo chống mưa, dây kéo từ cổ xuống đáy áo kín hoàn toàn. Class 2, 4 dải phản quang, vải dù PU 2000mm chống mưa vừa.',
      'Siêu nhẹ 100g/áo polyester nhẹ, gấp vào túi nhỏ 10x10cm. Dành cho người chạy bộ, đi xe đạp ban đêm, không cần bảo hộ cứng.',
      'Màu xanh navy với chữ SECURITY in phản quang sau lưng lớn. Class 1, 2 dải thân, vải polyester 150gsm, phù hợp bảo vệ phòng chức năng.',
      'Gile 5 túi: 2 ngực, 2 hông, 1 bên trên thợ điện. Dải phản quang vai+thân, nhiều ngăn đựng dụng cụ nhỏ, phù hợp thợ điện lắp đặt.',
      'Áo trẻ em 4-14 tuổi, dải phản quang cao cấp RA≥1000 cd/lux/m². Màu vàng nổi bật, vải cotton mềm, an toàn học sinh đi bộ đến trường.',
      'Thể thao chạy bộ polyester 85g/áo. Dải phản quang 360° cổ-vai-ngực-tay, nhìn rõ từ mọi hướng ban đêm, gọn nhẹ co giãn 4 chiều.',
      'Xanh lá cảnh sát giao thông Class 3, 5 dải full body. Dải 3M chính hãng bạc, in chữ CẢNH SÁT GIAO THÔNG bên lưng theo yêu cầu.',
      'Gile vải dù chống tia lửa hàn, dải phản quang chịu nhiệt 150°C. Dùng thợ hàn trong điều kiện cần nhìn thấy + chống tia lửa bắn.',
      'Logistics Class 2, túi ngực zip chứa điện thoại, bảng tên. Vải polyester 150gsm, in logo công ty lên lưng theo yêu cầu MOQ 10 áo.',
      'Tích hợp dải LED linh hoạt sạc USB, sáng ban đêm 3 chế độ. Ngoài dải phản quang thụ động còn có LED chủ động, an toàn gấp đôi.',
      'Vàng chanh Class 2, sáng nhất trong ánh sáng tự nhiên ban ngày. Dải bạc 50mm, 2 vòng thân+vai, vải 120gsm, ANSI/ISEA 107-2020.',
      'Áo liền quần (coverall) phản quang cam, Class 3 toàn thân. 7 dải: 2 cổ tay, 2 cổ chân, 2 thân, 1 vai. Kéo khóa trước từ cổ xuống.',
      'Bộ 2 màu: giám sát=cam, công nhân=vàng. Phân biệt vai trò ngay lập tức trên công trường, giảm nhầm lẫn chỉ đạo.',
      'Siêu nhẹ 100g, vải không dệt polyester 0.1mm. Dùng một lần hoặc một vài lần cho sự kiện, tham quan công trường, khách thăm.',
      'Chữ in NHÂN VIÊN KỸ THUẬT sau lưng 15cm phản quang. Dải thân đôi Class 2, phân biệt kỹ thuật viên với công nhân phổ thông.',
      'Kéo khóa 2 bên hông liên kết đai lưng co giãn. Điều chỉnh vòng eo 60-120cm mà không cần đặt nhiều size, tiết kiệm tồn kho.',
      'Cắt may ôm dáng nữ, không rộng thùng thình. Vải polyester 150gsm, dải phản quang đúng tiêu chuẩn EN ISO 20471 Class 2.',
      'In logo, tên công ty, mã màu theo yêu cầu. Vải 120gsm, dải chuẩn Class 2, MOQ 20 áo, giao hàng 7-10 ngày làm việc.',
      'Dây kéo YKK Japan chính hãng, cụm khóa kim loại kẽm. Bền hơn 200% so với khóa nhựa thông thường, không kẹt sau 1000 lần kéo.',
      'Dải phản quang mềm không cứng, uốn cong theo cơ thể. 3 dải 5cm trên vải 150gsm, thoáng không đổ mồ hôi, rửa tay thường xuyên.',
      'Nút chống vai thoáng mát nhất, không che kín toàn bộ vai. Phù hợp thời tiết nóng ẩm Việt Nam, thoáng gió từ vai xuống.',
      'Vai rộng 8cm bảo vệ khớp vai khỏi va đập nhẹ ngoài tác dụng phản quang. Dải ngực đôi ôm tốt, kích thước S/M/L/XL/XXL.',
      'Tháo ra là áo khoác gió thường, mặc vào có 3 dải phản quang. Đa năng cho người hay di chuyển giữa khu vực an toàn và nguy hiểm.',
      'Màu xanh navy bảo vệ với dải phản quang bạc, chuyên nghiệp hơn cam/vàng. Class 1, phù hợp bảo vệ cơ sở chính phủ, trung tâm thương mại.',
      'Lớp lưới bên trong tạo khe thoáng khí 5mm. Kết hợp cam và dải bạc, thêm lớp lưới vẫn đạt Class 2, mát hơn 30% theo đánh giá người dùng.',
      'Cổ bẻ bo vải mềm thay vì cổ đứng cứng. Kết thúc gile bằng khóa vải velcro ôm cổ, không gió lọt vào cổ mùa lạnh.',
      'In phản quang chữ SECURITY sau lưng lớn 20x5cm. Phân biệt ngay lập tức bảo vệ với công nhân từ xa 50m kể cả ban đêm.',
      'Thêu logo theo mẫu khách hàng, tối đa 5 màu chỉ. MOQ 10 áo, thời gian 7 ngày, màu logo không phai sau 100 lần giặt.',
      'Class 3 tay dài, 7 dải: 2 thân + 2 tay + 2 vai chéo + 1 hông. Tiêu chuẩn cao nhất EN ISO 20471:2013, phù hợp cảnh báo cấp cao.',
      'Lót lông nhân tạo Polar Fleece 200gsm bên trong áo dù. Ấm đến -10°C, dải phản quang Class 2 vẫn sáng, dây kéo kín cổ.',
      '4 túi zip: 2 ngực (điện thoại+máy đo) + 2 hông (dây cáp+đồng hồ). Thợ kỹ thuật mang đủ dụng cụ mà không cần ba lô.',
      'Cam sáng nhất có thể (fluorescent orange ANSI), Class 2. Dải 3M bạc cường độ cao RA≥550, nhìn rõ 300m ban đêm có đèn pha.',
      'Vải RPET từ chai nhựa tái chế, giảm 50% carbon footprint. Dải phản quang 3M cũng từ polyester tái chế, EN ISO 20471 Class 2.',
      'Yếm 2 dải bụng kết hợp 2 dải lưng, kiểu phổ biến châu Âu. Vải polyester nhẹ, buộc hông, không cần mặc áo phản quang toàn bộ.',
      'Oxford 600D dệt hai lớp, chịu rách theo tiêu chuẩn EN 388 cấp 2. Phù hợp công trường bê tông, thép, môi trường mài mòn cao.',
      'Đặt theo nhóm 10 áo in logo, tên công ty đồng nhất. Màu vàng/cam class 2, giao đồng bộ, tiết kiệm 15% so với đặt lẻ.',
      'Dải 3M 983 chống mài mòn, tẩy rửa mạnh vẫn sáng. Bền 100 lần giặt máy, 3 lần lăn sơn, vẫn đạt RA≥330 cd/lux/m². Bảo hành 1 năm.',
      '5 dải phản quang: 2 thân ngang + 2 vai chéo + 1 ngực dọc. Bao phủ 360° quan sát từ mọi góc độ, phù hợp làm đường, giao lộ.',
      'Thêu tên cá nhân, mã số nhân viên lên ngực phải. MOQ 1 áo, thêu máy công nghiệp không phai, màu chỉ theo yêu cầu.',
      'Áo gile nhà hàng-ẩm thực nhân viên phục vụ nhận biết. Màu xanh hoặc đen, dải phản quang 2.5cm mảnh, lịch sự không quá an toàn công nghiệp.',
      'Thêu logo công ty trong 3 ngày, sửa mẫu tùy ý trước khi sản xuất. Vải 150gsm, Class 2, đặt tối thiểu 10 áo, giao 5-7 ngày.',
      'Loại 1 Class 1 nhẹ nhất, dải phản quang tối thiểu theo tiêu chuẩn. Thoải mái cho xe đạp thể thao, chạy chậm, đi bộ ban đêm.',
      'Giao hàng: in hoặc thêu tên, mã đơn hàng. Màu cam Class 2, nhân viên shipper nhận biết ngay giữa dòng xe cộ đông đúc.',
      'Màu cam đặc biệt phối dải phản quang cổ tay viền xanh lam. Phân biệt ngay nhân viên vệ sinh môi trường, đẹp và an toàn.',
      'Sân bay, cảng hàng không: màu vàng-cam nổi bật trên băng chuyền. 3 dải thân + 2 dải vai, phù hợp nhân viên điều hướng sân đỗ.',
      'Màu xanh lá MRT/đường sắt, in số hiệu tuyến sau lưng. Class 2, thợ bảo trì đường ray dễ nhận biết, bền dầu mỡ đường sắt.',
      'Áo phản quang dành cho lái xe: mặc khi xuống xe trên đường. Thiết kế gọn nhẹ gấp vào hộp cốp xe, bắt buộc theo nghị định giao thông.',
      'Dùng cả ngày và đêm, trời nắng và mưa, mùa hè và mùa đông. Vải dù chống mưa nhẹ, dải phản quang bền thời tiết, Class 2.',
      'Tay ngắn phổ thông, Class 2, phù hợp mọi lứa tuổi công nhân. Giá tốt nhất phân khúc, mua số lượng lớn chiết khấu 20-30%.',
      'Vải thun phối dải phản quang 2.5cm, co giãn 4 chiều. Ấm hơn vải dù mùa lạnh, không bị gió lọt vào, phù hợp thời tiết Hà Nội.',
      'Cẩu tháp cần hiển thị tốt ở độ cao 100m+. Class 3, 7 dải chuẩn, dải 3M chính hãng bạc nhìn rõ từ đất lên bằng mắt thường.',
      'Áo liền quần toàn thân công trình, kéo khóa từ cổ xuống đáy. 5 dải phản quang, Class 3, vải dù chắc bền, nhiều túi đựng dụng cụ.',
      'Gile ngắn đến eo, không che quần áo bên dưới. Nhẹ 120g, gấp nhỏ bằng nắm tay, phù hợp cất gọn trong xe tải/balo.',
    ],
  },
  'Đồ bảo hộ PCCC': {
    names: [
      'Quần Áo Chữa Cháy Tiếp Cận Khu Vực Khói Lửa',
      'Mũ Chống Nhiệt PCCC Nomex Vành Toàn Phần',
      'Giày Chữa Cháy Cao Cổ Mũi Thép Lót Chì',
      'Găng Tay Chữa Cháy Nomex Cách Nhiệt 3 Lớp',
      'Đai Thắt Lưng PCCC Da Bò Kèm Móc Dụng Cụ',
      'Mặt Nạ Khói Lửa SCBA Bình Khí 30 Phút',
      'Bộ Quần Áo Chuyên Dụng Tiếp Cận Lửa Hóa Học',
      'Áo Chống Cháy Nomex FR Tiêu Chuẩn NFPA 1971',
    ],
    descs: [
      'Quần áo 2 lớp: ngoài Nomex chịu lửa, trong cách nhiệt Kevlar. Tiêu chuẩn EN 469:2020, mức 2, dải phản quang bạc chịu nhiệt.',
      'Mũ Nomex/Kevlar, vành che toàn mặt khi hạ xuống. Liner bên trong cách nhiệt, dây cằm co giãn, NFPA 1971 Structural.',
      'Giày da bò cao 30cm mũi thép 200J, lót chì chống đâm xuyên đinh. Đế cao su chịu nhiệt 300°C, EN 345 SB+P+A+WR, phản quang.',
      'Găng 3 lớp: Nomex ngoài, Kevlar bọc, cotton hút ẩm trong. Chịu nhiệt tiếp xúc 100°C 10s, bức xạ 10kW/m², NFPA 1971.',
      'Đai da bò 5cm, khóa nhanh, móc dụng cụ D-ring x4, vòng cho dây cứu hộ. Chịu lực 1500N, không bắt lửa, màu đen EN 340.',
      'Mặt nạ khép kín toàn mặt + bình khí nén 30 phút 300 bar. SCBA tự cung cấp, trọng lượng 9kg, tự kiểm tra khi mở van.',
      'Bộ đặc biệt tiếp cận lửa hóa học, lớp ngoài Zetex chịu 1000°C. Có mũ trùm, kính mặt, găng dài 45cm, giày phủ ngoài.',
      'Áo Nomex III® FR dày 4.5oz chịu hồ quang 8cal/cm². NFPA 1971 Proximity, phản quang 3M, cài Velcro nhanh, dùng cứu hỏa cấu trúc.',
    ],
  },
  'Đồ đi mưa - áo phao': {
    names: [
      'Áo Mưa Bộ PVC 2 Mảnh Phản Quang Công Trường',
      'Áo Phao Cứu Sinh Loại I CGA Inshore SOLAS',
      'Áo Mưa Bộ EVA Nhẹ Gấp Gọn Đi Phượt Leo Núi',
      'Phao Bơi Ôm Vải Cam Cứu Hộ Hình Vành Khăn',
      'Áo Mưa Có Mũ Liền Vải Dù Chống Thấm PU 3000mm',
      'Áo Phao Bơi Lội Trẻ Em Cánh Tay Phao Inflatable',
      'Áo Mưa Bộ PEVA Không Mùi Hóa Chất Thân Thiện',
      'Áo Phao Thuyền Kayak Buoyancy Aid Class 50N',
      'Áo Mưa Siêu Nhẹ 100g Pocket Poncho Compact',
      'Áo Phao Bán Tự Động 150N SOLAS Thuyền Viên',
      'Bộ Áo Mưa Đi Làm Đồng Bộ Mũ-Áo-Quần Phản Quang',
      'Áo Phao Trẻ Em Có Tay Nổi Nước 25-40kg Học Bơi',
    ],
    descs: [
      'Bộ PVC 2 mảnh áo+quần, dày 0.2mm, dải phản quang bạc. Dùng công trường ngoài trời, mưa to không thấm, khóa kéo bền, size S-3XL.',
      'Áo phao loại I CGA 150N tự phồng khi tiếp nước hoặc kéo tay. Cổ kéo dựng đầu, giữ mặt nổi mặt nước, SOLAS khuyến nghị tàu biển.',
      'EVA foam 8mm nhẹ 150g/bộ, gấp vào túi 15x10cm. Chống thấm PU 5000mm, dây mũ điều chỉnh, dùng đi xe máy, leo núi, phượt.',
      'Phao ôm vành khăn foam EPE Ø66cm, vải cam cứu hộ phản quang. Nổi 180N, gắn dây 30m kèm túi lưới, dùng cứu hộ hồ bơi, bãi biển.',
      'Mũ liền thân áo kéo khóa, vải dù taffeta PU 3000mm. Nhẹ 300g, cất gọn túi hông, thoáng tay áo đàn hồi, màu xanh/đỏ/vàng.',
      'Phao bơi trẻ em 3-6 tuổi, 2 cánh tay phao inflatable. Màu cam/xanh, khóa an toàn không tự tháo, dùng hồ bơi, biển có giám sát.',
      'Vải PEVA không PVC không BPA không mùi. Nhẹ 200g/bộ, chống thấm tốt, thân thiện da nhạy cảm, tái chế được sau khi dùng.',
      'Áo phao kayak Buoyancy Aid 50N, vải nylon nhẹ. Không phồng khi khô, ôm người tự do bơi, 6 móc điều chỉnh, khoang giữ foam.',
      'Poncho siêu nhẹ 100g, vải ripstop nhỏ gọn cất túi áo. Mặc nhanh 5 giây từ trên đầu xuống, dùng xem bóng đá, dã ngoại ngắn.',
      'Áo phao 150N bán tự động: kéo chốt phồng trong 5s hoặc tự động khi ngâm nước 10s. SOLAS thuyền viên, đèn flash+còi+gương.',
      'Bộ đồng bộ mũ-áo-quần phản quang cho đi làm mưa. Vải PVC nhẹ 0.15mm, dải bạc nhìn rõ đêm mưa, kéo khóa mũ điều chỉnh.',
      'Áo phao trẻ em 25-40kg, tay nổi EVA bên sườn. Khóa 3 điểm cẩn thận không tháo được, cổ cao đỡ đầu trẻ, màu sặc sỡ dễ tìm.',
    ],
  },
  'Đồng Phục Bảo Vệ': {
    names: [
      'Bộ Đồng Phục Bảo Vệ Nam Áo Sơ Mi Dài Tay Xanh Đen',
      'Bộ Đồng Phục Bảo Vệ Nữ Áo Sơ Mi Váy Chuyên Nghiệp',
      'Bộ Đồng Phục Bảo Vệ Mùa Hè Áo Ngắn Tay Quần Tây',
    ],
    descs: [
      'Áo sơ mi dài tay polyester 65/35, quần tây ống thẳng. Màu xanh đen, đường may kép chắc chắn, phù hợp bảo vệ tòa nhà văn phòng.',
      'Áo sơ mi nữ ôm dáng, váy đến đầu gối. Vải polyester mềm mại, màu xanh nhạt-trắng, đường may tinh tế, chuyên nghiệp dịch vụ.',
      'Áo ngắn tay cotton pique 65/35, quần tây nhẹ thoáng. Mùa hè dành riêng, màu xanh navy, dây đai da tổng hợp đi kèm.',
    ],
  },
  'Đồng Phục Bảo Vệ NEW': {
    names: [
      'Bộ Đồng Phục Bảo Vệ Mới Thiết Kế Phong Cách Hiện Đại',
      'Đồng Phục Bảo Vệ NEW Kiểu Tactical Nhiều Túi',
      'Bộ Đồng Phục Bảo Vệ Cao Cấp Collection 2025 Mới',
    ],
    descs: [
      'Thiết kế 2025 phong cách hiện đại, phối màu navy-đen. Vải TR 65/35 cao cấp chống nhăn, dễ ủi, đường may nghiêng tạo cảm giác thon.',
      'Kiểu tactical nhiều túi hộp: 2 ngực, 2 hông, 2 đùi. Vải ripstop chống rách, co giãn nhẹ, phù hợp bảo vệ năng động, tuần tra nhiều.',
      'Bộ cao cấp 2025 vải jacquard dệt tên công ty vào vải. Không cần thêu logo riêng, cúc inox, dây kéo YKK, lót vải mềm trong.',
    ],
  },
  'Ủng bảo hộ lao động': {
    names: [
      'Ủng Bảo Hộ PVC Mũi Thép Chống Hóa Chất Cao 35cm',
      'Ủng Cao Su Tự Nhiên Mũi Thép Chống Điện 1000V',
      'Ủng Đi Mưa Thấp Cổ Cao Su Mỏng Phản Quang',
      'Ủng Bảo Hộ Cổ Cao 40cm Lót Thép Đi Nơi Ẩm Ướt',
      'Ủng PVC Ngắn Cổ 20cm Chống Trơn SRA Nhà Máy',
      'Ủng Cao Su Đen Dày 4mm Mũi Thép Công Trường',
      'Ủng Bảo Hộ Nhiệt Cách Nhiệt Đến -40°C Kho Lạnh',
      'Ủng Chống Axit Đặc Biệt PVC Vàng Kho Hóa Chất',
      'Ủng Thể Thao Bảo Hộ Mũi Composite Nhẹ Nhà Máy',
      'Ủng Cao Su Màu Xanh Lá Thực Phẩm Chứng Nhận HACCP',
      'Ủng Bảo Hộ Cứng ABS Chống Tĩnh Điện ESD Phòng Sạch',
      'Ủng Lội Suối Cao Su Nhẹ EVA Đánh Cá Ngoài Trời',
      'Ủng Bảo Hộ Lớp Lót Flannel Giữ Ấm Mùa Đông',
      'Ủng PVC Phản Quang 3 Dải Công Trường Ban Đêm',
      'Ủng An Toàn Cao Su Khoản Cổ Điều Chỉnh Kéo Khóa',
      'Ủng Bảo Hộ Chống Đinh Lót Thép Mũi Thép SB+P',
      'Ủng Chống Nước Thoáng Khí Gore-Tex Mũi Composite',
      'Ủng Bảo Hộ Thời Trang PU Mũi Thép Thiết Kế Hiện Đại',
      'Ủng Làm Ruộng Nông Nghiệp Cao Su Nhẹ Cổ Ngắn',
      'Ủng Bảo Hộ Cao Cấp Nhật Bản Mishima Mũi Thép JIS',
      'Ủng Đi Biển Lội Sình Lầy EVA Đúc Nguyên Khối',
      'Ủng Chống Trượt Bếp Nhà Hàng SRA Cao Su Phẳng',
    ],
    descs: [
      'PVC nguyên sinh cổ cao 35cm, mũi thép 200J, lót thép chống đâm xuyên. Chống acid loãng, kiềm nhẹ, dầu mỡ. EN ISO 20345 S5.',
      'Cao su lưu hóa tự nhiên cổ cao 38cm, mũi thép 200J. Cách điện 1000V AC/1500V DC IEC 60745, dùng thợ điện đứng nước.',
      'Cổ thấp 18cm cao su mỏng nhẹ, đế phẳng SRA chống trơn dầu ăn. Phản quang bên ngoài, đi mưa hoặc vệ sinh nhà máy thực phẩm.',
      'Cổ cao 40cm che đùi, mũi thép 200J, lót thép. Dùng đi lội sình lầy nông nghiệp, công trường nước ngập, bảo tồn đất ướt.',
      'Cổ ngắn 20cm PVC, đế xẻ rãnh sâu chống trơn SRA. Nhẹ 600g/đôi, phù hợp kho mát thực phẩm, nhà máy bia, xưởng rửa xe.',
      'Cao su đen dày 4mm cổ cao 35cm, mũi thép đúc liền. Chịu lực va 200J, nén 15kN, không thấm nước, phù hợp công trường xây dựng.',
      'Cách nhiệt lõi foam đặc biệt đến -40°C, cổ cao 38cm. Đế cao su không cứng giòn mùa đông, lót vải fleece giữ ấm, kho đông lạnh.',
      'PVC màu vàng đặc biệt nhận biết khu vực hóa chất. Chống H₂SO₄ 20%, HCl 10%, NaOH 30%, dài 40cm bảo vệ đến bắp chân.',
      'Mũi composite không kim loại, nhẹ hơn mũi thép 30%. Nhựa ABS mũi, đế EVA+cao su nhẹ, phù hợp nhà máy cần không có từ tính.',
      'Cao su xanh lá HACCP chứng nhận, mũi nhựa ABS không kim loại. Dùng chế biến thực phẩm, bếp nhà hàng, kho lạnh thực phẩm.',
      'ABS cứng ESD điện trở 10⁶-10⁹Ω, mũi nhựa không từ tính. Phòng sạch ISO, vùng nổ ATEX zone 1-2, dùng chip điện tử, dầu khí.',
      'EVA nguyên khối siêu nhẹ 300g/đôi, không thấm nước. Dùng đánh cá, lội suối nhẹ, nông nghiệp, không có mũi bảo vệ.',
      'Lót flannel polyester 3mm giữ ấm đến 0°C. PVC cổ cao 30cm, mũi thép 200J, dùng kho lạnh thực phẩm không quá lạnh.',
      'Dải phản quang 3 vòng 25mm bên ngoài ủng PVC. Nhìn rõ ban đêm từ 80m, công nhân công trường tối hoặc đêm muộn.',
      'Cao su cổ cao có khóa kéo bên sườn dễ mang-tháo nhanh. Điều chỉnh bắp chân qua khóa cài bằng kim loại inox, mũi thép 200J.',
      'Mũi thép 200J + lót thép chống đâm xuyên đinh. Tiêu chuẩn SB+P EN ISO 20345, cao su dày 4mm, cổ 32cm, không thấm nước.',
      'Màng Gore-Tex 3 lớp chống thấm tuyệt đối thoáng hơi. Mũi composite nhẹ 200J, đế cao su SRC chống trơn, phù hợp địa hình ướt-khô.',
      'Thiết kế thời trang PU leather bóng, mũi thép ẩn không lộ. Đế cao su thời trang SRA, phù hợp nhân viên kho thương mại, showroom.',
      'Cao su thiên nhiên mỏng nhẹ 400g cổ ngắn 20cm. Dùng ruộng lúa, đi vườn, thu hoạch rau củ, không cần bảo vệ mũi.',
      'Nhật Bản Mishima JIS T8101, mũi thép 200J tiêu chuẩn Nhật. Cao su tự nhiên cổ cao 38cm, chất lượng xuất khẩu, bền 3-5 năm sử dụng.',
      'EVA đúc nguyên khối không đường may, không thấm nước tuyệt đối. Nhẹ 350g, lội sình lầy, ruộng, biển, dễ rửa sạch ngay vòi nước.',
      'Cao su phẳng đế 5mm rãnh phẳng chống trơn sàn gạch bếp. SRA tiêu chuẩn, cổ thấp 15cm, không có mũi bảo vệ, gọn nhẹ bếp nhà hàng.',
    ],
  },
};

module.exports = productData;
